using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Windows.Forms;
using DpSdkEngLib;
using DPSDKOPSLib;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
namespace _4PosBackOffice.NET
{
	[Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
	partial class frmStockItemHistory
	{
		#region "Windows Form Designer generated code "
		[System.Diagnostics.DebuggerNonUserCode()]
		public frmStockItemHistory() : base()
		{
			FormClosed += frmStockItemHistory_FormClosed;
			KeyPress += frmStockItemHistory_KeyPress;
			Resize += frmStockItemHistory_Resize;
			Load += frmStockItemHistory_Load;
			//This call is required by the Windows Form Designer.
			InitializeComponent();
		}
//Form overrides dispose to clean up the component list.
		[System.Diagnostics.DebuggerNonUserCode()]
		protected override void Dispose(bool Disposing)
		{
			if (Disposing) {
				if ((components != null)) {
					components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}
//Required by the Windows Form Designer
		private System.ComponentModel.IContainer components;
		public System.Windows.Forms.ToolTip ToolTip1;
		private System.Windows.Forms.Button withEventsField_cmdClose;
		public System.Windows.Forms.Button cmdClose {
			get { return withEventsField_cmdClose; }
			set {
				if (withEventsField_cmdClose != null) {
					withEventsField_cmdClose.Click -= cmdClose_Click;
				}
				withEventsField_cmdClose = value;
				if (withEventsField_cmdClose != null) {
					withEventsField_cmdClose.Click += cmdClose_Click;
				}
			}
		}
		public System.Windows.Forms.Panel picButtons;
		public System.Windows.Forms.Label _Label1_17;
		public System.Windows.Forms.Label _Label1_16;
		public System.Windows.Forms.Label _Label1_15;
		public System.Windows.Forms.Label _Label1_4;
		public System.Windows.Forms.Label _Label1_14;
		public System.Windows.Forms.Label _Label1_13;
		public System.Windows.Forms.Label _Label1_12;
		public System.Windows.Forms.Label _Label1_11;
		public System.Windows.Forms.Label _Label1_10;
		public System.Windows.Forms.Label _Label1_9;
		public System.Windows.Forms.Label _Label1_8;
		public System.Windows.Forms.Label _Label1_7;
		public System.Windows.Forms.Label _Label1_6;
		public System.Windows.Forms.Label _Label1_5;
		public System.Windows.Forms.Label _Label1_3;
		public System.Windows.Forms.Label _lblFieldCurr_0;
		public System.Windows.Forms.Label _lblField_38;
		public System.Windows.Forms.Label _lblField_37;
		public System.Windows.Forms.Label _lblField_36;
		public System.Windows.Forms.Label _lblField_35;
		public System.Windows.Forms.Label _lblField_34;
		public System.Windows.Forms.Label _lblField_33;
		public System.Windows.Forms.Label _lblField_32;
		public System.Windows.Forms.Label _lblField_31;
		public System.Windows.Forms.Label _lblField_30;
		public System.Windows.Forms.Label _lblField_29;
		public System.Windows.Forms.Label _lblField_28;
		public System.Windows.Forms.Label _lblField_27;
		public System.Windows.Forms.Label _lblField_26;
		public System.Windows.Forms.Label _lblField_25;
		public System.Windows.Forms.Label _lblField_24;
		public System.Windows.Forms.Label _lblField_23;
		public System.Windows.Forms.Label _lblField_22;
		public System.Windows.Forms.Label _lblField_21;
		public System.Windows.Forms.Label _lblField_20;
		public System.Windows.Forms.Label _lblField_19;
		public System.Windows.Forms.Label _lblField_18;
		public System.Windows.Forms.Label _lblField_17;
		public System.Windows.Forms.Label _lblField_16;
		public System.Windows.Forms.Label _lblField_15;
		public System.Windows.Forms.Label _lblField_14;
		public System.Windows.Forms.Label _lblField_13;
		public System.Windows.Forms.Label _lblField_12;
		public System.Windows.Forms.Label _lblField_11;
		public System.Windows.Forms.Label _lblField_10;
		public System.Windows.Forms.Label _lblField_9;
		public System.Windows.Forms.Label _lblField_8;
		public System.Windows.Forms.Label _lblField_7;
		public System.Windows.Forms.Label _lblField_6;
		public System.Windows.Forms.Label _lblField_5;
		public System.Windows.Forms.Label _lblField_4;
		public System.Windows.Forms.Label _lblField_3;
		public System.Windows.Forms.Label _lblField_2;
		public System.Windows.Forms.Label _lblField_1;
		public System.Windows.Forms.Label _lblField_0;
		public System.Windows.Forms.Label _Label1_0;
		public System.Windows.Forms.Label _Label1_1;
		public System.Windows.Forms.Label _Label1_2;
		//Public WithEvents Label1 As Microsoft.VisualBasic.Compatibility.VB6.LabelArray
		//Public WithEvents lblField As Microsoft.VisualBasic.Compatibility.VB6.LabelArray
		//Public WithEvents lblFieldCurr As Microsoft.VisualBasic.Compatibility.VB6.LabelArray
//NOTE: The following procedure is required by the Windows Form Designer
//It can be modified using the Windows Form Designer.
//Do not modify it using the code editor.
		[System.Diagnostics.DebuggerStepThrough()]
		private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(frmStockItemHistory));
			this.components = new System.ComponentModel.Container();
			this.ToolTip1 = new System.Windows.Forms.ToolTip(components);
			this.picButtons = new System.Windows.Forms.Panel();
			this.cmdClose = new System.Windows.Forms.Button();
			this._Label1_17 = new System.Windows.Forms.Label();
			this._Label1_16 = new System.Windows.Forms.Label();
			this._Label1_15 = new System.Windows.Forms.Label();
			this._Label1_4 = new System.Windows.Forms.Label();
			this._Label1_14 = new System.Windows.Forms.Label();
			this._Label1_13 = new System.Windows.Forms.Label();
			this._Label1_12 = new System.Windows.Forms.Label();
			this._Label1_11 = new System.Windows.Forms.Label();
			this._Label1_10 = new System.Windows.Forms.Label();
			this._Label1_9 = new System.Windows.Forms.Label();
			this._Label1_8 = new System.Windows.Forms.Label();
			this._Label1_7 = new System.Windows.Forms.Label();
			this._Label1_6 = new System.Windows.Forms.Label();
			this._Label1_5 = new System.Windows.Forms.Label();
			this._Label1_3 = new System.Windows.Forms.Label();
			this._lblFieldCurr_0 = new System.Windows.Forms.Label();
			this._lblField_38 = new System.Windows.Forms.Label();
			this._lblField_37 = new System.Windows.Forms.Label();
			this._lblField_36 = new System.Windows.Forms.Label();
			this._lblField_35 = new System.Windows.Forms.Label();
			this._lblField_34 = new System.Windows.Forms.Label();
			this._lblField_33 = new System.Windows.Forms.Label();
			this._lblField_32 = new System.Windows.Forms.Label();
			this._lblField_31 = new System.Windows.Forms.Label();
			this._lblField_30 = new System.Windows.Forms.Label();
			this._lblField_29 = new System.Windows.Forms.Label();
			this._lblField_28 = new System.Windows.Forms.Label();
			this._lblField_27 = new System.Windows.Forms.Label();
			this._lblField_26 = new System.Windows.Forms.Label();
			this._lblField_25 = new System.Windows.Forms.Label();
			this._lblField_24 = new System.Windows.Forms.Label();
			this._lblField_23 = new System.Windows.Forms.Label();
			this._lblField_22 = new System.Windows.Forms.Label();
			this._lblField_21 = new System.Windows.Forms.Label();
			this._lblField_20 = new System.Windows.Forms.Label();
			this._lblField_19 = new System.Windows.Forms.Label();
			this._lblField_18 = new System.Windows.Forms.Label();
			this._lblField_17 = new System.Windows.Forms.Label();
			this._lblField_16 = new System.Windows.Forms.Label();
			this._lblField_15 = new System.Windows.Forms.Label();
			this._lblField_14 = new System.Windows.Forms.Label();
			this._lblField_13 = new System.Windows.Forms.Label();
			this._lblField_12 = new System.Windows.Forms.Label();
			this._lblField_11 = new System.Windows.Forms.Label();
			this._lblField_10 = new System.Windows.Forms.Label();
			this._lblField_9 = new System.Windows.Forms.Label();
			this._lblField_8 = new System.Windows.Forms.Label();
			this._lblField_7 = new System.Windows.Forms.Label();
			this._lblField_6 = new System.Windows.Forms.Label();
			this._lblField_5 = new System.Windows.Forms.Label();
			this._lblField_4 = new System.Windows.Forms.Label();
			this._lblField_3 = new System.Windows.Forms.Label();
			this._lblField_2 = new System.Windows.Forms.Label();
			this._lblField_1 = new System.Windows.Forms.Label();
			this._lblField_0 = new System.Windows.Forms.Label();
			this._Label1_0 = new System.Windows.Forms.Label();
			this._Label1_1 = new System.Windows.Forms.Label();
			this._Label1_2 = new System.Windows.Forms.Label();
			//Me.Label1 = New Microsoft.VisualBasic.Compatibility.VB6.LabelArray(components)
			//'Me.lblField = New Microsoft.VisualBasic.Compatibility.VB6.LabelArray(components)
			//Me.lblFieldCurr = New Microsoft.VisualBasic.Compatibility.VB6.LabelArray(components)
			this.picButtons.SuspendLayout();
			this.SuspendLayout();
			this.ToolTip1.Active = true;
			//CType(Me.Label1, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.lblField, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.lblFieldCurr, System.ComponentModel.ISupportInitialize).BeginInit()
			this.BackColor = System.Drawing.Color.FromArgb(224, 224, 224);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.Text = "Stock item Sales History";
			this.ClientSize = new System.Drawing.Size(538, 204);
			this.Location = new System.Drawing.Point(73, 22);
			this.ControlBox = false;
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Enabled = true;
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.ShowInTaskbar = true;
			this.HelpButton = false;
			this.WindowState = System.Windows.Forms.FormWindowState.Normal;
			this.Name = "frmStockItemHistory";
			this.picButtons.Dock = System.Windows.Forms.DockStyle.Top;
			this.picButtons.BackColor = System.Drawing.Color.Blue;
			this.picButtons.Size = new System.Drawing.Size(538, 38);
			this.picButtons.Location = new System.Drawing.Point(0, 0);
			this.picButtons.TabIndex = 1;
			this.picButtons.TabStop = false;
			this.picButtons.CausesValidation = true;
			this.picButtons.Enabled = true;
			this.picButtons.ForeColor = System.Drawing.SystemColors.ControlText;
			this.picButtons.Cursor = System.Windows.Forms.Cursors.Default;
			this.picButtons.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.picButtons.Visible = true;
			this.picButtons.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.picButtons.Name = "picButtons";
			this.cmdClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdClose.Text = "E&xit";
			this.cmdClose.Size = new System.Drawing.Size(73, 29);
			this.cmdClose.Location = new System.Drawing.Point(459, 3);
			this.cmdClose.TabIndex = 0;
			this.cmdClose.TabStop = false;
			this.cmdClose.BackColor = System.Drawing.SystemColors.Control;
			this.cmdClose.CausesValidation = true;
			this.cmdClose.Enabled = true;
			this.cmdClose.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdClose.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdClose.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdClose.Name = "cmdClose";
			this._Label1_17.Text = "units per case";
			this._Label1_17.Size = new System.Drawing.Size(66, 13);
			this._Label1_17.Location = new System.Drawing.Point(420, 79);
			this._Label1_17.TabIndex = 59;
			this._Label1_17.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_17.BackColor = System.Drawing.Color.Transparent;
			this._Label1_17.Enabled = true;
			this._Label1_17.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_17.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_17.UseMnemonic = true;
			this._Label1_17.Visible = true;
			this._Label1_17.AutoSize = true;
			this._Label1_17.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_17.Name = "_Label1_17";
			this._Label1_16.Text = "cases in stock";
			this._Label1_16.Size = new System.Drawing.Size(68, 13);
			this._Label1_16.Location = new System.Drawing.Point(300, 79);
			this._Label1_16.TabIndex = 58;
			this._Label1_16.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_16.BackColor = System.Drawing.Color.Transparent;
			this._Label1_16.Enabled = true;
			this._Label1_16.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_16.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_16.UseMnemonic = true;
			this._Label1_16.Visible = true;
			this._Label1_16.AutoSize = true;
			this._Label1_16.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_16.Name = "_Label1_16";
			this._Label1_15.Text = "Current Units in Stock";
			this._Label1_15.Size = new System.Drawing.Size(103, 13);
			this._Label1_15.Location = new System.Drawing.Point(144, 79);
			this._Label1_15.TabIndex = 57;
			this._Label1_15.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_15.BackColor = System.Drawing.Color.Transparent;
			this._Label1_15.Enabled = true;
			this._Label1_15.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_15.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_15.UseMnemonic = true;
			this._Label1_15.Visible = true;
			this._Label1_15.AutoSize = true;
			this._Label1_15.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_15.Name = "_Label1_15";
			this._Label1_4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_4.Text = "2";
			this._Label1_4.Size = new System.Drawing.Size(36, 19);
			this._Label1_4.Location = new System.Drawing.Point(102, 108);
			this._Label1_4.TabIndex = 56;
			this._Label1_4.BackColor = System.Drawing.Color.Transparent;
			this._Label1_4.Enabled = true;
			this._Label1_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_4.UseMnemonic = true;
			this._Label1_4.Visible = true;
			this._Label1_4.AutoSize = false;
			this._Label1_4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_4.Name = "_Label1_4";
			this._Label1_14.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_14.Text = "12";
			this._Label1_14.Size = new System.Drawing.Size(36, 19);
			this._Label1_14.Location = new System.Drawing.Point(492, 108);
			this._Label1_14.TabIndex = 55;
			this._Label1_14.BackColor = System.Drawing.Color.Transparent;
			this._Label1_14.Enabled = true;
			this._Label1_14.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_14.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_14.UseMnemonic = true;
			this._Label1_14.Visible = true;
			this._Label1_14.AutoSize = false;
			this._Label1_14.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_14.Name = "_Label1_14";
			this._Label1_13.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_13.Text = "11";
			this._Label1_13.Size = new System.Drawing.Size(36, 19);
			this._Label1_13.Location = new System.Drawing.Point(453, 108);
			this._Label1_13.TabIndex = 54;
			this._Label1_13.BackColor = System.Drawing.Color.Transparent;
			this._Label1_13.Enabled = true;
			this._Label1_13.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_13.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_13.UseMnemonic = true;
			this._Label1_13.Visible = true;
			this._Label1_13.AutoSize = false;
			this._Label1_13.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_13.Name = "_Label1_13";
			this._Label1_12.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_12.Text = "10";
			this._Label1_12.Size = new System.Drawing.Size(36, 19);
			this._Label1_12.Location = new System.Drawing.Point(414, 108);
			this._Label1_12.TabIndex = 53;
			this._Label1_12.BackColor = System.Drawing.Color.Transparent;
			this._Label1_12.Enabled = true;
			this._Label1_12.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_12.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_12.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_12.UseMnemonic = true;
			this._Label1_12.Visible = true;
			this._Label1_12.AutoSize = false;
			this._Label1_12.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_12.Name = "_Label1_12";
			this._Label1_11.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_11.Text = "9";
			this._Label1_11.Size = new System.Drawing.Size(36, 19);
			this._Label1_11.Location = new System.Drawing.Point(375, 108);
			this._Label1_11.TabIndex = 52;
			this._Label1_11.BackColor = System.Drawing.Color.Transparent;
			this._Label1_11.Enabled = true;
			this._Label1_11.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_11.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_11.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_11.UseMnemonic = true;
			this._Label1_11.Visible = true;
			this._Label1_11.AutoSize = false;
			this._Label1_11.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_11.Name = "_Label1_11";
			this._Label1_10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_10.Text = "8";
			this._Label1_10.Size = new System.Drawing.Size(36, 19);
			this._Label1_10.Location = new System.Drawing.Point(336, 108);
			this._Label1_10.TabIndex = 51;
			this._Label1_10.BackColor = System.Drawing.Color.Transparent;
			this._Label1_10.Enabled = true;
			this._Label1_10.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_10.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_10.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_10.UseMnemonic = true;
			this._Label1_10.Visible = true;
			this._Label1_10.AutoSize = false;
			this._Label1_10.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_10.Name = "_Label1_10";
			this._Label1_9.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_9.Text = "7";
			this._Label1_9.Size = new System.Drawing.Size(36, 19);
			this._Label1_9.Location = new System.Drawing.Point(297, 108);
			this._Label1_9.TabIndex = 50;
			this._Label1_9.BackColor = System.Drawing.Color.Transparent;
			this._Label1_9.Enabled = true;
			this._Label1_9.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_9.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_9.UseMnemonic = true;
			this._Label1_9.Visible = true;
			this._Label1_9.AutoSize = false;
			this._Label1_9.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_9.Name = "_Label1_9";
			this._Label1_8.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_8.Text = "6";
			this._Label1_8.Size = new System.Drawing.Size(36, 19);
			this._Label1_8.Location = new System.Drawing.Point(258, 108);
			this._Label1_8.TabIndex = 49;
			this._Label1_8.BackColor = System.Drawing.Color.Transparent;
			this._Label1_8.Enabled = true;
			this._Label1_8.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_8.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_8.UseMnemonic = true;
			this._Label1_8.Visible = true;
			this._Label1_8.AutoSize = false;
			this._Label1_8.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_8.Name = "_Label1_8";
			this._Label1_7.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_7.Text = "5";
			this._Label1_7.Size = new System.Drawing.Size(36, 19);
			this._Label1_7.Location = new System.Drawing.Point(219, 108);
			this._Label1_7.TabIndex = 48;
			this._Label1_7.BackColor = System.Drawing.Color.Transparent;
			this._Label1_7.Enabled = true;
			this._Label1_7.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_7.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_7.UseMnemonic = true;
			this._Label1_7.Visible = true;
			this._Label1_7.AutoSize = false;
			this._Label1_7.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_7.Name = "_Label1_7";
			this._Label1_6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_6.Text = "4";
			this._Label1_6.Size = new System.Drawing.Size(36, 19);
			this._Label1_6.Location = new System.Drawing.Point(180, 108);
			this._Label1_6.TabIndex = 47;
			this._Label1_6.BackColor = System.Drawing.Color.Transparent;
			this._Label1_6.Enabled = true;
			this._Label1_6.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_6.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_6.UseMnemonic = true;
			this._Label1_6.Visible = true;
			this._Label1_6.AutoSize = false;
			this._Label1_6.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_6.Name = "_Label1_6";
			this._Label1_5.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_5.Text = "3";
			this._Label1_5.Size = new System.Drawing.Size(36, 19);
			this._Label1_5.Location = new System.Drawing.Point(141, 108);
			this._Label1_5.TabIndex = 46;
			this._Label1_5.BackColor = System.Drawing.Color.Transparent;
			this._Label1_5.Enabled = true;
			this._Label1_5.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_5.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_5.UseMnemonic = true;
			this._Label1_5.Visible = true;
			this._Label1_5.AutoSize = false;
			this._Label1_5.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_5.Name = "_Label1_5";
			this._Label1_3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			this._Label1_3.Text = "1";
			this._Label1_3.Size = new System.Drawing.Size(36, 19);
			this._Label1_3.Location = new System.Drawing.Point(63, 108);
			this._Label1_3.TabIndex = 45;
			this._Label1_3.BackColor = System.Drawing.Color.Transparent;
			this._Label1_3.Enabled = true;
			this._Label1_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_3.UseMnemonic = true;
			this._Label1_3.Visible = true;
			this._Label1_3.AutoSize = false;
			this._Label1_3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._Label1_3.Name = "_Label1_3";
			this._lblFieldCurr_0.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblFieldCurr_0.Text = "0";
			this._lblFieldCurr_0.Size = new System.Drawing.Size(42, 17);
			this._lblFieldCurr_0.Location = new System.Drawing.Point(372, 78);
			this._lblFieldCurr_0.TabIndex = 41;
			this._lblFieldCurr_0.BackColor = System.Drawing.Color.Transparent;
			this._lblFieldCurr_0.Enabled = true;
			this._lblFieldCurr_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblFieldCurr_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblFieldCurr_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblFieldCurr_0.UseMnemonic = true;
			this._lblFieldCurr_0.Visible = true;
			this._lblFieldCurr_0.AutoSize = false;
			this._lblFieldCurr_0.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblFieldCurr_0.Name = "_lblFieldCurr_0";
			this._lblField_38.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_38.Text = "0";
			this._lblField_38.Size = new System.Drawing.Size(36, 17);
			this._lblField_38.Location = new System.Drawing.Point(492, 78);
			this._lblField_38.TabIndex = 40;
			this._lblField_38.BackColor = System.Drawing.Color.Transparent;
			this._lblField_38.Enabled = true;
			this._lblField_38.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_38.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_38.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_38.UseMnemonic = true;
			this._lblField_38.Visible = true;
			this._lblField_38.AutoSize = false;
			this._lblField_38.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_38.Name = "_lblField_38";
			this._lblField_37.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_37.Text = "0";
			this._lblField_37.Size = new System.Drawing.Size(42, 17);
			this._lblField_37.Location = new System.Drawing.Point(252, 78);
			this._lblField_37.TabIndex = 39;
			this._lblField_37.BackColor = System.Drawing.Color.Transparent;
			this._lblField_37.Enabled = true;
			this._lblField_37.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_37.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_37.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_37.UseMnemonic = true;
			this._lblField_37.Visible = true;
			this._lblField_37.AutoSize = false;
			this._lblField_37.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_37.Name = "_lblField_37";
			this._lblField_36.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_36.BackColor = System.Drawing.Color.White;
			this._lblField_36.Text = "0";
			this._lblField_36.Size = new System.Drawing.Size(36, 17);
			this._lblField_36.Location = new System.Drawing.Point(492, 177);
			this._lblField_36.TabIndex = 38;
			this._lblField_36.Enabled = true;
			this._lblField_36.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_36.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_36.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_36.UseMnemonic = true;
			this._lblField_36.Visible = true;
			this._lblField_36.AutoSize = false;
			this._lblField_36.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_36.Name = "_lblField_36";
			this._lblField_35.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_35.BackColor = System.Drawing.Color.White;
			this._lblField_35.Text = "0";
			this._lblField_35.Size = new System.Drawing.Size(36, 17);
			this._lblField_35.Location = new System.Drawing.Point(453, 177);
			this._lblField_35.TabIndex = 37;
			this._lblField_35.Enabled = true;
			this._lblField_35.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_35.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_35.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_35.UseMnemonic = true;
			this._lblField_35.Visible = true;
			this._lblField_35.AutoSize = false;
			this._lblField_35.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_35.Name = "_lblField_35";
			this._lblField_34.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_34.BackColor = System.Drawing.Color.White;
			this._lblField_34.Text = "0";
			this._lblField_34.Size = new System.Drawing.Size(36, 17);
			this._lblField_34.Location = new System.Drawing.Point(414, 177);
			this._lblField_34.TabIndex = 36;
			this._lblField_34.Enabled = true;
			this._lblField_34.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_34.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_34.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_34.UseMnemonic = true;
			this._lblField_34.Visible = true;
			this._lblField_34.AutoSize = false;
			this._lblField_34.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_34.Name = "_lblField_34";
			this._lblField_33.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_33.BackColor = System.Drawing.Color.White;
			this._lblField_33.Text = "0";
			this._lblField_33.Size = new System.Drawing.Size(36, 17);
			this._lblField_33.Location = new System.Drawing.Point(375, 177);
			this._lblField_33.TabIndex = 35;
			this._lblField_33.Enabled = true;
			this._lblField_33.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_33.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_33.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_33.UseMnemonic = true;
			this._lblField_33.Visible = true;
			this._lblField_33.AutoSize = false;
			this._lblField_33.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_33.Name = "_lblField_33";
			this._lblField_32.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_32.BackColor = System.Drawing.Color.White;
			this._lblField_32.Text = "0";
			this._lblField_32.Size = new System.Drawing.Size(36, 17);
			this._lblField_32.Location = new System.Drawing.Point(336, 177);
			this._lblField_32.TabIndex = 34;
			this._lblField_32.Enabled = true;
			this._lblField_32.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_32.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_32.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_32.UseMnemonic = true;
			this._lblField_32.Visible = true;
			this._lblField_32.AutoSize = false;
			this._lblField_32.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_32.Name = "_lblField_32";
			this._lblField_31.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_31.BackColor = System.Drawing.Color.White;
			this._lblField_31.Text = "0";
			this._lblField_31.Size = new System.Drawing.Size(36, 17);
			this._lblField_31.Location = new System.Drawing.Point(297, 177);
			this._lblField_31.TabIndex = 33;
			this._lblField_31.Enabled = true;
			this._lblField_31.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_31.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_31.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_31.UseMnemonic = true;
			this._lblField_31.Visible = true;
			this._lblField_31.AutoSize = false;
			this._lblField_31.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_31.Name = "_lblField_31";
			this._lblField_30.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_30.BackColor = System.Drawing.Color.White;
			this._lblField_30.Text = "0";
			this._lblField_30.Size = new System.Drawing.Size(36, 17);
			this._lblField_30.Location = new System.Drawing.Point(258, 177);
			this._lblField_30.TabIndex = 32;
			this._lblField_30.Enabled = true;
			this._lblField_30.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_30.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_30.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_30.UseMnemonic = true;
			this._lblField_30.Visible = true;
			this._lblField_30.AutoSize = false;
			this._lblField_30.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_30.Name = "_lblField_30";
			this._lblField_29.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_29.BackColor = System.Drawing.Color.White;
			this._lblField_29.Text = "0";
			this._lblField_29.Size = new System.Drawing.Size(36, 17);
			this._lblField_29.Location = new System.Drawing.Point(219, 177);
			this._lblField_29.TabIndex = 31;
			this._lblField_29.Enabled = true;
			this._lblField_29.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_29.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_29.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_29.UseMnemonic = true;
			this._lblField_29.Visible = true;
			this._lblField_29.AutoSize = false;
			this._lblField_29.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_29.Name = "_lblField_29";
			this._lblField_28.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_28.BackColor = System.Drawing.Color.White;
			this._lblField_28.Text = "0";
			this._lblField_28.Size = new System.Drawing.Size(36, 17);
			this._lblField_28.Location = new System.Drawing.Point(180, 177);
			this._lblField_28.TabIndex = 30;
			this._lblField_28.Enabled = true;
			this._lblField_28.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_28.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_28.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_28.UseMnemonic = true;
			this._lblField_28.Visible = true;
			this._lblField_28.AutoSize = false;
			this._lblField_28.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_28.Name = "_lblField_28";
			this._lblField_27.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_27.BackColor = System.Drawing.Color.White;
			this._lblField_27.Text = "0";
			this._lblField_27.Size = new System.Drawing.Size(36, 17);
			this._lblField_27.Location = new System.Drawing.Point(141, 177);
			this._lblField_27.TabIndex = 29;
			this._lblField_27.Enabled = true;
			this._lblField_27.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_27.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_27.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_27.UseMnemonic = true;
			this._lblField_27.Visible = true;
			this._lblField_27.AutoSize = false;
			this._lblField_27.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_27.Name = "_lblField_27";
			this._lblField_26.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_26.BackColor = System.Drawing.Color.White;
			this._lblField_26.Text = "0";
			this._lblField_26.Size = new System.Drawing.Size(36, 17);
			this._lblField_26.Location = new System.Drawing.Point(102, 177);
			this._lblField_26.TabIndex = 28;
			this._lblField_26.Enabled = true;
			this._lblField_26.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_26.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_26.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_26.UseMnemonic = true;
			this._lblField_26.Visible = true;
			this._lblField_26.AutoSize = false;
			this._lblField_26.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_26.Name = "_lblField_26";
			this._lblField_25.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_25.BackColor = System.Drawing.Color.White;
			this._lblField_25.Text = "0";
			this._lblField_25.Size = new System.Drawing.Size(36, 17);
			this._lblField_25.Location = new System.Drawing.Point(63, 177);
			this._lblField_25.TabIndex = 27;
			this._lblField_25.Enabled = true;
			this._lblField_25.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_25.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_25.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_25.UseMnemonic = true;
			this._lblField_25.Visible = true;
			this._lblField_25.AutoSize = false;
			this._lblField_25.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_25.Name = "_lblField_25";
			this._lblField_24.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_24.BackColor = System.Drawing.Color.White;
			this._lblField_24.Text = "0";
			this._lblField_24.Size = new System.Drawing.Size(36, 17);
			this._lblField_24.Location = new System.Drawing.Point(492, 153);
			this._lblField_24.TabIndex = 26;
			this._lblField_24.Enabled = true;
			this._lblField_24.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_24.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_24.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_24.UseMnemonic = true;
			this._lblField_24.Visible = true;
			this._lblField_24.AutoSize = false;
			this._lblField_24.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_24.Name = "_lblField_24";
			this._lblField_23.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_23.BackColor = System.Drawing.Color.White;
			this._lblField_23.Text = "0";
			this._lblField_23.Size = new System.Drawing.Size(36, 17);
			this._lblField_23.Location = new System.Drawing.Point(453, 153);
			this._lblField_23.TabIndex = 25;
			this._lblField_23.Enabled = true;
			this._lblField_23.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_23.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_23.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_23.UseMnemonic = true;
			this._lblField_23.Visible = true;
			this._lblField_23.AutoSize = false;
			this._lblField_23.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_23.Name = "_lblField_23";
			this._lblField_22.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_22.BackColor = System.Drawing.Color.White;
			this._lblField_22.Text = "0";
			this._lblField_22.Size = new System.Drawing.Size(36, 17);
			this._lblField_22.Location = new System.Drawing.Point(414, 153);
			this._lblField_22.TabIndex = 24;
			this._lblField_22.Enabled = true;
			this._lblField_22.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_22.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_22.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_22.UseMnemonic = true;
			this._lblField_22.Visible = true;
			this._lblField_22.AutoSize = false;
			this._lblField_22.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_22.Name = "_lblField_22";
			this._lblField_21.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_21.BackColor = System.Drawing.Color.White;
			this._lblField_21.Text = "0";
			this._lblField_21.Size = new System.Drawing.Size(36, 17);
			this._lblField_21.Location = new System.Drawing.Point(375, 153);
			this._lblField_21.TabIndex = 23;
			this._lblField_21.Enabled = true;
			this._lblField_21.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_21.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_21.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_21.UseMnemonic = true;
			this._lblField_21.Visible = true;
			this._lblField_21.AutoSize = false;
			this._lblField_21.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_21.Name = "_lblField_21";
			this._lblField_20.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_20.BackColor = System.Drawing.Color.White;
			this._lblField_20.Text = "0";
			this._lblField_20.Size = new System.Drawing.Size(36, 17);
			this._lblField_20.Location = new System.Drawing.Point(336, 153);
			this._lblField_20.TabIndex = 22;
			this._lblField_20.Enabled = true;
			this._lblField_20.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_20.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_20.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_20.UseMnemonic = true;
			this._lblField_20.Visible = true;
			this._lblField_20.AutoSize = false;
			this._lblField_20.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_20.Name = "_lblField_20";
			this._lblField_19.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_19.BackColor = System.Drawing.Color.White;
			this._lblField_19.Text = "0";
			this._lblField_19.Size = new System.Drawing.Size(36, 17);
			this._lblField_19.Location = new System.Drawing.Point(297, 153);
			this._lblField_19.TabIndex = 21;
			this._lblField_19.Enabled = true;
			this._lblField_19.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_19.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_19.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_19.UseMnemonic = true;
			this._lblField_19.Visible = true;
			this._lblField_19.AutoSize = false;
			this._lblField_19.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_19.Name = "_lblField_19";
			this._lblField_18.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_18.BackColor = System.Drawing.Color.White;
			this._lblField_18.Text = "0";
			this._lblField_18.Size = new System.Drawing.Size(36, 17);
			this._lblField_18.Location = new System.Drawing.Point(258, 153);
			this._lblField_18.TabIndex = 20;
			this._lblField_18.Enabled = true;
			this._lblField_18.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_18.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_18.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_18.UseMnemonic = true;
			this._lblField_18.Visible = true;
			this._lblField_18.AutoSize = false;
			this._lblField_18.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_18.Name = "_lblField_18";
			this._lblField_17.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_17.BackColor = System.Drawing.Color.White;
			this._lblField_17.Text = "0";
			this._lblField_17.Size = new System.Drawing.Size(36, 17);
			this._lblField_17.Location = new System.Drawing.Point(219, 153);
			this._lblField_17.TabIndex = 19;
			this._lblField_17.Enabled = true;
			this._lblField_17.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_17.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_17.UseMnemonic = true;
			this._lblField_17.Visible = true;
			this._lblField_17.AutoSize = false;
			this._lblField_17.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_17.Name = "_lblField_17";
			this._lblField_16.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_16.BackColor = System.Drawing.Color.White;
			this._lblField_16.Text = "0";
			this._lblField_16.Size = new System.Drawing.Size(36, 17);
			this._lblField_16.Location = new System.Drawing.Point(180, 153);
			this._lblField_16.TabIndex = 18;
			this._lblField_16.Enabled = true;
			this._lblField_16.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_16.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_16.UseMnemonic = true;
			this._lblField_16.Visible = true;
			this._lblField_16.AutoSize = false;
			this._lblField_16.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_16.Name = "_lblField_16";
			this._lblField_15.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_15.BackColor = System.Drawing.Color.White;
			this._lblField_15.Text = "0";
			this._lblField_15.Size = new System.Drawing.Size(36, 17);
			this._lblField_15.Location = new System.Drawing.Point(141, 153);
			this._lblField_15.TabIndex = 17;
			this._lblField_15.Enabled = true;
			this._lblField_15.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_15.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_15.UseMnemonic = true;
			this._lblField_15.Visible = true;
			this._lblField_15.AutoSize = false;
			this._lblField_15.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_15.Name = "_lblField_15";
			this._lblField_14.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_14.BackColor = System.Drawing.Color.White;
			this._lblField_14.Text = "0";
			this._lblField_14.Size = new System.Drawing.Size(36, 17);
			this._lblField_14.Location = new System.Drawing.Point(102, 153);
			this._lblField_14.TabIndex = 16;
			this._lblField_14.Enabled = true;
			this._lblField_14.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_14.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_14.UseMnemonic = true;
			this._lblField_14.Visible = true;
			this._lblField_14.AutoSize = false;
			this._lblField_14.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_14.Name = "_lblField_14";
			this._lblField_13.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_13.BackColor = System.Drawing.Color.White;
			this._lblField_13.Text = "0";
			this._lblField_13.Size = new System.Drawing.Size(36, 17);
			this._lblField_13.Location = new System.Drawing.Point(63, 153);
			this._lblField_13.TabIndex = 15;
			this._lblField_13.Enabled = true;
			this._lblField_13.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_13.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_13.UseMnemonic = true;
			this._lblField_13.Visible = true;
			this._lblField_13.AutoSize = false;
			this._lblField_13.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_13.Name = "_lblField_13";
			this._lblField_12.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_12.BackColor = System.Drawing.Color.White;
			this._lblField_12.Text = "0";
			this._lblField_12.Size = new System.Drawing.Size(36, 17);
			this._lblField_12.Location = new System.Drawing.Point(492, 129);
			this._lblField_12.TabIndex = 14;
			this._lblField_12.Enabled = true;
			this._lblField_12.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_12.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_12.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_12.UseMnemonic = true;
			this._lblField_12.Visible = true;
			this._lblField_12.AutoSize = false;
			this._lblField_12.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_12.Name = "_lblField_12";
			this._lblField_11.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_11.BackColor = System.Drawing.Color.White;
			this._lblField_11.Text = "0";
			this._lblField_11.Size = new System.Drawing.Size(36, 17);
			this._lblField_11.Location = new System.Drawing.Point(453, 129);
			this._lblField_11.TabIndex = 13;
			this._lblField_11.Enabled = true;
			this._lblField_11.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_11.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_11.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_11.UseMnemonic = true;
			this._lblField_11.Visible = true;
			this._lblField_11.AutoSize = false;
			this._lblField_11.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_11.Name = "_lblField_11";
			this._lblField_10.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_10.BackColor = System.Drawing.Color.White;
			this._lblField_10.Text = "0";
			this._lblField_10.Size = new System.Drawing.Size(36, 17);
			this._lblField_10.Location = new System.Drawing.Point(414, 129);
			this._lblField_10.TabIndex = 12;
			this._lblField_10.Enabled = true;
			this._lblField_10.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_10.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_10.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_10.UseMnemonic = true;
			this._lblField_10.Visible = true;
			this._lblField_10.AutoSize = false;
			this._lblField_10.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_10.Name = "_lblField_10";
			this._lblField_9.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_9.BackColor = System.Drawing.Color.White;
			this._lblField_9.Text = "0";
			this._lblField_9.Size = new System.Drawing.Size(36, 17);
			this._lblField_9.Location = new System.Drawing.Point(375, 129);
			this._lblField_9.TabIndex = 11;
			this._lblField_9.Enabled = true;
			this._lblField_9.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_9.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_9.UseMnemonic = true;
			this._lblField_9.Visible = true;
			this._lblField_9.AutoSize = false;
			this._lblField_9.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_9.Name = "_lblField_9";
			this._lblField_8.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_8.BackColor = System.Drawing.Color.White;
			this._lblField_8.Text = "0";
			this._lblField_8.Size = new System.Drawing.Size(36, 17);
			this._lblField_8.Location = new System.Drawing.Point(336, 129);
			this._lblField_8.TabIndex = 10;
			this._lblField_8.Enabled = true;
			this._lblField_8.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_8.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_8.UseMnemonic = true;
			this._lblField_8.Visible = true;
			this._lblField_8.AutoSize = false;
			this._lblField_8.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_8.Name = "_lblField_8";
			this._lblField_7.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_7.BackColor = System.Drawing.Color.White;
			this._lblField_7.Text = "0";
			this._lblField_7.Size = new System.Drawing.Size(36, 17);
			this._lblField_7.Location = new System.Drawing.Point(297, 129);
			this._lblField_7.TabIndex = 9;
			this._lblField_7.Enabled = true;
			this._lblField_7.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_7.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_7.UseMnemonic = true;
			this._lblField_7.Visible = true;
			this._lblField_7.AutoSize = false;
			this._lblField_7.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_7.Name = "_lblField_7";
			this._lblField_6.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_6.BackColor = System.Drawing.Color.White;
			this._lblField_6.Text = "0";
			this._lblField_6.Size = new System.Drawing.Size(36, 17);
			this._lblField_6.Location = new System.Drawing.Point(258, 129);
			this._lblField_6.TabIndex = 8;
			this._lblField_6.Enabled = true;
			this._lblField_6.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_6.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_6.UseMnemonic = true;
			this._lblField_6.Visible = true;
			this._lblField_6.AutoSize = false;
			this._lblField_6.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_6.Name = "_lblField_6";
			this._lblField_5.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_5.BackColor = System.Drawing.Color.White;
			this._lblField_5.Text = "0";
			this._lblField_5.Size = new System.Drawing.Size(36, 17);
			this._lblField_5.Location = new System.Drawing.Point(219, 129);
			this._lblField_5.TabIndex = 7;
			this._lblField_5.Enabled = true;
			this._lblField_5.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_5.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_5.UseMnemonic = true;
			this._lblField_5.Visible = true;
			this._lblField_5.AutoSize = false;
			this._lblField_5.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_5.Name = "_lblField_5";
			this._lblField_4.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_4.BackColor = System.Drawing.Color.White;
			this._lblField_4.Text = "0";
			this._lblField_4.Size = new System.Drawing.Size(36, 17);
			this._lblField_4.Location = new System.Drawing.Point(180, 129);
			this._lblField_4.TabIndex = 6;
			this._lblField_4.Enabled = true;
			this._lblField_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_4.UseMnemonic = true;
			this._lblField_4.Visible = true;
			this._lblField_4.AutoSize = false;
			this._lblField_4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_4.Name = "_lblField_4";
			this._lblField_3.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_3.BackColor = System.Drawing.Color.White;
			this._lblField_3.Text = "0";
			this._lblField_3.Size = new System.Drawing.Size(36, 17);
			this._lblField_3.Location = new System.Drawing.Point(141, 129);
			this._lblField_3.TabIndex = 5;
			this._lblField_3.Enabled = true;
			this._lblField_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_3.UseMnemonic = true;
			this._lblField_3.Visible = true;
			this._lblField_3.AutoSize = false;
			this._lblField_3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_3.Name = "_lblField_3";
			this._lblField_2.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_2.BackColor = System.Drawing.Color.White;
			this._lblField_2.Text = "0";
			this._lblField_2.Size = new System.Drawing.Size(36, 17);
			this._lblField_2.Location = new System.Drawing.Point(102, 129);
			this._lblField_2.TabIndex = 4;
			this._lblField_2.Enabled = true;
			this._lblField_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_2.UseMnemonic = true;
			this._lblField_2.Visible = true;
			this._lblField_2.AutoSize = false;
			this._lblField_2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_2.Name = "_lblField_2";
			this._lblField_1.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblField_1.BackColor = System.Drawing.Color.White;
			this._lblField_1.Text = "0";
			this._lblField_1.Size = new System.Drawing.Size(36, 17);
			this._lblField_1.Location = new System.Drawing.Point(63, 129);
			this._lblField_1.TabIndex = 3;
			this._lblField_1.Enabled = true;
			this._lblField_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_1.UseMnemonic = true;
			this._lblField_1.Visible = true;
			this._lblField_1.AutoSize = false;
			this._lblField_1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_1.Name = "_lblField_1";
			this._lblField_0.Text = "Label1";
			this._lblField_0.Size = new System.Drawing.Size(520, 25);
			this._lblField_0.Location = new System.Drawing.Point(9, 45);
			this._lblField_0.TabIndex = 2;
			this._lblField_0.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._lblField_0.BackColor = System.Drawing.Color.Transparent;
			this._lblField_0.Enabled = true;
			this._lblField_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblField_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblField_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblField_0.UseMnemonic = true;
			this._lblField_0.Visible = true;
			this._lblField_0.AutoSize = false;
			this._lblField_0.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this._lblField_0.Name = "_lblField_0";
			this._Label1_0.BackColor = System.Drawing.Color.FromArgb(255, 128, 128);
			this._Label1_0.Text = "Daily";
			this._Label1_0.Size = new System.Drawing.Size(526, 22);
			this._Label1_0.Location = new System.Drawing.Point(6, 127);
			this._Label1_0.TabIndex = 42;
			this._Label1_0.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_0.Enabled = true;
			this._Label1_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_0.UseMnemonic = true;
			this._Label1_0.Visible = true;
			this._Label1_0.AutoSize = false;
			this._Label1_0.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_0.Name = "_Label1_0";
			this._Label1_1.BackColor = System.Drawing.Color.FromArgb(255, 255, 128);
			this._Label1_1.Text = "Weekly";
			this._Label1_1.Size = new System.Drawing.Size(526, 22);
			this._Label1_1.Location = new System.Drawing.Point(6, 150);
			this._Label1_1.TabIndex = 43;
			this._Label1_1.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_1.Enabled = true;
			this._Label1_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_1.UseMnemonic = true;
			this._Label1_1.Visible = true;
			this._Label1_1.AutoSize = false;
			this._Label1_1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_1.Name = "_Label1_1";
			this._Label1_2.BackColor = System.Drawing.Color.FromArgb(128, 255, 128);
			this._Label1_2.Text = "Monthly";
			this._Label1_2.Size = new System.Drawing.Size(526, 22);
			this._Label1_2.Location = new System.Drawing.Point(6, 174);
			this._Label1_2.TabIndex = 44;
			this._Label1_2.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._Label1_2.Enabled = true;
			this._Label1_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._Label1_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._Label1_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._Label1_2.UseMnemonic = true;
			this._Label1_2.Visible = true;
			this._Label1_2.AutoSize = false;
			this._Label1_2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._Label1_2.Name = "_Label1_2";
			this.Controls.Add(picButtons);
			this.Controls.Add(_Label1_17);
			this.Controls.Add(_Label1_16);
			this.Controls.Add(_Label1_15);
			this.Controls.Add(_Label1_4);
			this.Controls.Add(_Label1_14);
			this.Controls.Add(_Label1_13);
			this.Controls.Add(_Label1_12);
			this.Controls.Add(_Label1_11);
			this.Controls.Add(_Label1_10);
			this.Controls.Add(_Label1_9);
			this.Controls.Add(_Label1_8);
			this.Controls.Add(_Label1_7);
			this.Controls.Add(_Label1_6);
			this.Controls.Add(_Label1_5);
			this.Controls.Add(_Label1_3);
			this.Controls.Add(_lblFieldCurr_0);
			this.Controls.Add(_lblField_38);
			this.Controls.Add(_lblField_37);
			this.Controls.Add(_lblField_36);
			this.Controls.Add(_lblField_35);
			this.Controls.Add(_lblField_34);
			this.Controls.Add(_lblField_33);
			this.Controls.Add(_lblField_32);
			this.Controls.Add(_lblField_31);
			this.Controls.Add(_lblField_30);
			this.Controls.Add(_lblField_29);
			this.Controls.Add(_lblField_28);
			this.Controls.Add(_lblField_27);
			this.Controls.Add(_lblField_26);
			this.Controls.Add(_lblField_25);
			this.Controls.Add(_lblField_24);
			this.Controls.Add(_lblField_23);
			this.Controls.Add(_lblField_22);
			this.Controls.Add(_lblField_21);
			this.Controls.Add(_lblField_20);
			this.Controls.Add(_lblField_19);
			this.Controls.Add(_lblField_18);
			this.Controls.Add(_lblField_17);
			this.Controls.Add(_lblField_16);
			this.Controls.Add(_lblField_15);
			this.Controls.Add(_lblField_14);
			this.Controls.Add(_lblField_13);
			this.Controls.Add(_lblField_12);
			this.Controls.Add(_lblField_11);
			this.Controls.Add(_lblField_10);
			this.Controls.Add(_lblField_9);
			this.Controls.Add(_lblField_8);
			this.Controls.Add(_lblField_7);
			this.Controls.Add(_lblField_6);
			this.Controls.Add(_lblField_5);
			this.Controls.Add(_lblField_4);
			this.Controls.Add(_lblField_3);
			this.Controls.Add(_lblField_2);
			this.Controls.Add(_lblField_1);
			this.Controls.Add(_lblField_0);
			this.Controls.Add(_Label1_0);
			this.Controls.Add(_Label1_1);
			this.Controls.Add(_Label1_2);
			this.picButtons.Controls.Add(cmdClose);
			//Me.Label1.SetIndex(_Label1_17, CType(17, Short))
			//Me.Label1.SetIndex(_Label1_16, CType(16, Short))
			//Me.Label1.SetIndex(_Label1_15, CType(15, Short))
			//Me.Label1.SetIndex(_Label1_4, CType(4, Short))
			//Me.Label1.SetIndex(_Label1_14, CType(14, Short))
			//Me.Label1.SetIndex(_Label1_13, CType(13, Short))
			//Me.Label1.SetIndex(_Label1_12, CType(12, Short))
			//Me.Label1.SetIndex(_Label1_11, CType(11, Short))
			//Me.Label1.SetIndex(_Label1_10, CType(10, Short))
			//Me.Label1.SetIndex(_Label1_9, CType(9, Short))
			//Me.Label1.SetIndex(_Label1_8, CType(8, Short))
			//Me.Label1.SetIndex(_Label1_7, CType(7, Short))
			//Me.Label1.SetIndex(_Label1_6, CType(6, Short))
			//Me.Label1.SetIndex(_Label1_5, CType(5, Short))
			//Me.Label1.SetIndex(_Label1_3, CType(3, Short))
			//Me.Label1.SetIndex(_Label1_0, CType(0, Short))
			//Me.Label1.SetIndex(_Label1_1, CType(1, Short))
			//Me.Label1.SetIndex(_Label1_2, CType(2, Short))
			//Me.lblField.SetIndex(_lblField_38, CType(38, Short))
			//Me.lblField.SetIndex(_lblField_37, CType(37, Short))
			//Me.lblField.SetIndex(_lblField_36, CType(36, Short))
			//M() 'e.lblField.SetIndex(_lblField_35, CType(35, Short))
			//M() ''e.lblField.SetIndex(_lblField_34, CType(34, Short))
			//M() 'e.lblField.SetIndex(_lblField_33, CType(33, Short))
			//Me.lblField.SetIndex(_lblField_32, CType(32, Short))
			//Me.lblField.SetIndex(_lblField_31, CType(31, Short))
			//Me.lblField.SetIndex(_lblField_30, CType(30, Short))
			//Me.lblField.SetIndex(_lblField_29, CType(29, Short))
			//Me.lblField.SetIndex(_lblField_28, CType(28, Short))
			//Me.lblField.SetIndex(_lblField_27, CType(27, Short))
			//M() ''e.lblField.SetIndex(_lblField_26, CType(26, Short))
			//M() 'e.lblField.SetIndex(_lblField_25, CType(25, Short))
			//Me() ''.lblField.SetIndex(_lblField_24, CType(24, Short))
			//Me.lblField.SetIndex(_lblField_23, CType(23, Short))
			//Me.lblField.SetIndex(_lblField_22, CType(22, Short))
			//'Me.lblField.SetIndex(_lblField_21, CType(21, Short))
			//M() 'e.lblField.SetIndex(_lblField_20, CType(20, Short))
			//M() 'e.lblField.SetIndex(_lblField_19, CType(19, Short))
			//Me.lblField.SetIndex(_lblField_18, CType(18, Short))
			//'Me.lblField.SetIndex(_lblField_17, CType(17, Short))
			//Me.lblField.SetIndex(_lblField_16, CType(16, Short))
			//Me.lblField.SetIndex(_lblField_15, CType(15, Short))
			//Me.lblField.SetIndex(_lblField_14, CType(14, Short))
			//Me.lblField.SetIndex(_lblField_13, CType(13, Short))
			//Me.lblField.SetIndex(_lblField_12, CType(12, Short))
			//Me.lblField.SetIndex(_lblField_11, CType(11, Short))
			//M() ''e.lblField.SetIndex(_lblField_10, CType(10, Short))
			//M() 'e.lblField.SetIndex(_lblField_9, CType(9, Short))
			//M() ''e.lblField.SetIndex(_lblField_8, CType(8, Short))
			//M() 'e.lblField.SetIndex(_lblField_7, CType(7, Short))
			//M() 'e.lblField.SetIndex(_lblField_6, CType(6, Short))
			//Me.lblField.SetIndex(_lblField_5, CType(5, Short))
			//Me.lblField.SetIndex(_lblField_4, CType(4, Short))
			//Me.lblField.SetIndex(_lblField_3, CType(3, Short))
			//Me.lblField.SetIndex(_lblField_2, CType(2, Short))
			//Me.lblField.SetIndex(_lblField_1, CType(1, Short))
			//Me.lblField.SetIndex(_lblField_0, CType(0, Short))
			//Me.lblFieldCurr.SetIndex(_lblFieldCurr_0, CType(0, Short))
			//CType(Me.lblFieldCurr, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.lblField, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.Label1, System.ComponentModel.ISupportInitialize).EndInit()
			this.picButtons.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
