using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Windows.Forms;
using DpSdkEngLib;
using DPSDKOPSLib;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
namespace _4PosBackOffice.NET
{
	[Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
	partial class frmSupplier
	{
		#region "Windows Form Designer generated code "
		[System.Diagnostics.DebuggerNonUserCode()]
		public frmSupplier() : base()
		{
			FormClosed += frmSupplier_FormClosed;
			KeyDown += frmSupplier_KeyDown;
			Resize += frmSupplier_Resize;
			Load += frmSupplier_Load;
			//This call is required by the Windows Form Designer.
			InitializeComponent();
		}
//Form overrides dispose to clean up the component list.
		[System.Diagnostics.DebuggerNonUserCode()]
		protected override void Dispose(bool Disposing)
		{
			if (Disposing) {
				if ((components != null)) {
					components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}
//Required by the Windows Form Designer
		private System.ComponentModel.IContainer components;
		public System.Windows.Forms.ToolTip ToolTip1;
		public System.Windows.Forms.CheckBox _chkFields_1;
		public System.Windows.Forms.TextBox _txtFields_28;
		public System.Windows.Forms.TextBox _txtFields_27;
		public System.Windows.Forms.TextBox _txtFields_26;
		public System.Windows.Forms.TextBox _txtFields_1;
		public System.Windows.Forms.TextBox _txtFloatNegative_11;
		public System.Windows.Forms.TextBox _txtFloatNegative_12;
		public System.Windows.Forms.TextBox _txtFloatNegative_13;
		public System.Windows.Forms.TextBox _txtFloatNegative_14;
		public System.Windows.Forms.TextBox _txtFloatNegative_15;
		public System.Windows.Forms.TextBox _txtFloatNegative_16;
		public System.Windows.Forms.TextBox _txtFloatNegative_17;
		public System.Windows.Forms.TextBox _txtFloatNegative_18;
		public System.Windows.Forms.TextBox _txtFields_2;
		public System.Windows.Forms.TextBox _txtFields_6;
		public System.Windows.Forms.TextBox _txtFields_7;
		public System.Windows.Forms.TextBox _txtFields_8;
		public System.Windows.Forms.TextBox _txtFields_9;
		public System.Windows.Forms.TextBox _txtFloat_13;
		public System.Windows.Forms.TextBox _txtFloat_14;
		public System.Windows.Forms.TextBox _txtFloat_15;
		public System.Windows.Forms.TextBox _txtFloat_16;
		public System.Windows.Forms.TextBox _txtFloat_17;
		private System.Windows.Forms.Button withEventsField_cmdStatement;
		public System.Windows.Forms.Button cmdStatement {
			get { return withEventsField_cmdStatement; }
			set {
				if (withEventsField_cmdStatement != null) {
					withEventsField_cmdStatement.Click -= cmdStatement_Click;
				}
				withEventsField_cmdStatement = value;
				if (withEventsField_cmdStatement != null) {
					withEventsField_cmdStatement.Click += cmdStatement_Click;
				}
			}
		}
		private System.Windows.Forms.Button withEventsField_cmdCancel;
		public System.Windows.Forms.Button cmdCancel {
			get { return withEventsField_cmdCancel; }
			set {
				if (withEventsField_cmdCancel != null) {
					withEventsField_cmdCancel.Click -= cmdCancel_Click;
				}
				withEventsField_cmdCancel = value;
				if (withEventsField_cmdCancel != null) {
					withEventsField_cmdCancel.Click += cmdCancel_Click;
				}
			}
		}
		private System.Windows.Forms.Button withEventsField_cmdClose;
		public System.Windows.Forms.Button cmdClose {
			get { return withEventsField_cmdClose; }
			set {
				if (withEventsField_cmdClose != null) {
					withEventsField_cmdClose.Click -= cmdClose_Click;
				}
				withEventsField_cmdClose = value;
				if (withEventsField_cmdClose != null) {
					withEventsField_cmdClose.Click += cmdClose_Click;
				}
			}
		}
		public System.Windows.Forms.Panel picButtons;
		public myDataGridView cmbTemplate;
		public System.Windows.Forms.Label _lbl_4;
		public System.Windows.Forms.Label _lbl_3;
		public System.Windows.Forms.Label _lbl_2;
		public System.Windows.Forms.Label _lblLabels_38;
		public System.Windows.Forms.Label _lblLabels_37;
		public System.Windows.Forms.Label _lblLabels_36;
		public System.Windows.Forms.Label _lblLabels_35;
		public System.Windows.Forms.Label _lblLabels_33;
		public System.Windows.Forms.Label _lblLabels_32;
		public System.Windows.Forms.Label _lblLabels_31;
		public System.Windows.Forms.Label _lblLabels_30;
		public System.Windows.Forms.Label _lblLabels_29;
		public System.Windows.Forms.Label _lblLabels_28;
		public System.Windows.Forms.Label _lblLabels_27;
		public System.Windows.Forms.Label _lblLabels_26;
		public System.Windows.Forms.Label _lbl_1;
		public System.Windows.Forms.Label _lbl_0;
		public System.Windows.Forms.Label _lblLabels_2;
		public System.Windows.Forms.Label _lblLabels_6;
		public System.Windows.Forms.Label _lblLabels_7;
		public System.Windows.Forms.Label _lblLabels_8;
		public System.Windows.Forms.Label _lblLabels_9;
		public System.Windows.Forms.Label _lblLabels_13;
		public System.Windows.Forms.Label _lblLabels_14;
		public System.Windows.Forms.Label _lblLabels_15;
		public System.Windows.Forms.Label _lblLabels_16;
		public System.Windows.Forms.Label _lblLabels_17;
		public Microsoft.VisualBasic.PowerPacks.RectangleShape _Shape1_0;
		public Microsoft.VisualBasic.PowerPacks.RectangleShape _Shape1_1;
		public Microsoft.VisualBasic.PowerPacks.RectangleShape _Shape1_2;
		public Microsoft.VisualBasic.PowerPacks.RectangleShape _Shape1_3;
		//Public WithEvents chkFields As Microsoft.VisualBasic.Compatibility.VB6.CheckBoxArray
		//Public WithEvents lbl As Microsoft.VisualBasic.Compatibility.VB6.LabelArray
		//Public WithEvents lblLabels As Microsoft.VisualBasic.Compatibility.VB6.LabelArray
		//Public WithEvents txtFields As Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray
		//Public WithEvents txtFloat As Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray
		//Public WithEvents txtFloatNegative As Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray
		public RectangleShapeArray Shape1;
		public Microsoft.VisualBasic.PowerPacks.ShapeContainer ShapeContainer1;
//NOTE: The following procedure is required by the Windows Form Designer
//It can be modified using the Windows Form Designer.
//Do not modify it using the code editor.
		[System.Diagnostics.DebuggerStepThrough()]
		private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(frmSupplier));
			this.components = new System.ComponentModel.Container();
			this.ToolTip1 = new System.Windows.Forms.ToolTip(components);
			this.ShapeContainer1 = new Microsoft.VisualBasic.PowerPacks.ShapeContainer();
			this._chkFields_1 = new System.Windows.Forms.CheckBox();
			this._txtFields_28 = new System.Windows.Forms.TextBox();
			this._txtFields_27 = new System.Windows.Forms.TextBox();
			this._txtFields_26 = new System.Windows.Forms.TextBox();
			this._txtFields_1 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_11 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_12 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_13 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_14 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_15 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_16 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_17 = new System.Windows.Forms.TextBox();
			this._txtFloatNegative_18 = new System.Windows.Forms.TextBox();
			this._txtFields_2 = new System.Windows.Forms.TextBox();
			this._txtFields_6 = new System.Windows.Forms.TextBox();
			this._txtFields_7 = new System.Windows.Forms.TextBox();
			this._txtFields_8 = new System.Windows.Forms.TextBox();
			this._txtFields_9 = new System.Windows.Forms.TextBox();
			this._txtFloat_13 = new System.Windows.Forms.TextBox();
			this._txtFloat_14 = new System.Windows.Forms.TextBox();
			this._txtFloat_15 = new System.Windows.Forms.TextBox();
			this._txtFloat_16 = new System.Windows.Forms.TextBox();
			this._txtFloat_17 = new System.Windows.Forms.TextBox();
			this.picButtons = new System.Windows.Forms.Panel();
			this.cmdStatement = new System.Windows.Forms.Button();
			this.cmdCancel = new System.Windows.Forms.Button();
			this.cmdClose = new System.Windows.Forms.Button();
			this.cmbTemplate = new myDataGridView();
			this._lbl_4 = new System.Windows.Forms.Label();
			this._lbl_3 = new System.Windows.Forms.Label();
			this._lbl_2 = new System.Windows.Forms.Label();
			this._lblLabels_38 = new System.Windows.Forms.Label();
			this._lblLabels_37 = new System.Windows.Forms.Label();
			this._lblLabels_36 = new System.Windows.Forms.Label();
			this._lblLabels_35 = new System.Windows.Forms.Label();
			this._lblLabels_33 = new System.Windows.Forms.Label();
			this._lblLabels_32 = new System.Windows.Forms.Label();
			this._lblLabels_31 = new System.Windows.Forms.Label();
			this._lblLabels_30 = new System.Windows.Forms.Label();
			this._lblLabels_29 = new System.Windows.Forms.Label();
			this._lblLabels_28 = new System.Windows.Forms.Label();
			this._lblLabels_27 = new System.Windows.Forms.Label();
			this._lblLabels_26 = new System.Windows.Forms.Label();
			this._lbl_1 = new System.Windows.Forms.Label();
			this._lbl_0 = new System.Windows.Forms.Label();
			this._lblLabels_2 = new System.Windows.Forms.Label();
			this._lblLabels_6 = new System.Windows.Forms.Label();
			this._lblLabels_7 = new System.Windows.Forms.Label();
			this._lblLabels_8 = new System.Windows.Forms.Label();
			this._lblLabels_9 = new System.Windows.Forms.Label();
			this._lblLabels_13 = new System.Windows.Forms.Label();
			this._lblLabels_14 = new System.Windows.Forms.Label();
			this._lblLabels_15 = new System.Windows.Forms.Label();
			this._lblLabels_16 = new System.Windows.Forms.Label();
			this._lblLabels_17 = new System.Windows.Forms.Label();
			this._Shape1_0 = new Microsoft.VisualBasic.PowerPacks.RectangleShape();
			this._Shape1_1 = new Microsoft.VisualBasic.PowerPacks.RectangleShape();
			this._Shape1_2 = new Microsoft.VisualBasic.PowerPacks.RectangleShape();
			this._Shape1_3 = new Microsoft.VisualBasic.PowerPacks.RectangleShape();
			//Me.chkFields = New Microsoft.VisualBasic.Compatibility.VB6.CheckBoxArray(components)
			//Me.lbl = New Microsoft.VisualBasic.Compatibility.VB6.LabelArray(components)
			//Me.lblLabels = New Microsoft.VisualBasic.Compatibility.VB6.LabelArray(components)
			//Me.txtFields = New Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray(components)
			//Me.txtFloat = New Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray(components)
			//Me.txtFloatNegative = New Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray(components)
			this.Shape1 = new RectangleShapeArray(components);
			this.picButtons.SuspendLayout();
			this.SuspendLayout();
			this.ToolTip1.Active = true;
			((System.ComponentModel.ISupportInitialize)this.cmbTemplate).BeginInit();
			//CType(Me.chkFields, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.lbl, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.lblLabels, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.txtFields, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.txtFloat, System.ComponentModel.ISupportInitialize).BeginInit()
			//CType(Me.txtFloatNegative, System.ComponentModel.ISupportInitialize).BeginInit()
			((System.ComponentModel.ISupportInitialize)this.Shape1).BeginInit();
			this.BackColor = System.Drawing.Color.FromArgb(224, 224, 224);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.Text = "Edit Supplier Details";
			this.ClientSize = new System.Drawing.Size(661, 347);
			this.Location = new System.Drawing.Point(73, 22);
			this.ControlBox = false;
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Enabled = true;
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.ShowInTaskbar = true;
			this.HelpButton = false;
			this.WindowState = System.Windows.Forms.FormWindowState.Normal;
			this.Name = "frmSupplier";
			this._chkFields_1.CheckAlign = System.Drawing.ContentAlignment.MiddleRight;
			this._chkFields_1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkFields_1.BackColor = System.Drawing.Color.FromArgb(192, 192, 255);
			this._chkFields_1.Text = "Disable this Supplier";
			this._chkFields_1.ForeColor = System.Drawing.SystemColors.WindowText;
			this._chkFields_1.Size = new System.Drawing.Size(118, 13);
			this._chkFields_1.Location = new System.Drawing.Point(210, 216);
			this._chkFields_1.TabIndex = 15;
			this._chkFields_1.CausesValidation = true;
			this._chkFields_1.Enabled = true;
			this._chkFields_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._chkFields_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._chkFields_1.Appearance = System.Windows.Forms.Appearance.Normal;
			this._chkFields_1.TabStop = true;
			this._chkFields_1.CheckState = System.Windows.Forms.CheckState.Unchecked;
			this._chkFields_1.Visible = true;
			this._chkFields_1.Name = "_chkFields_1";
			this._txtFields_28.AutoSize = false;
			this._txtFields_28.Size = new System.Drawing.Size(168, 19);
			this._txtFields_28.Location = new System.Drawing.Point(476, 65);
			this._txtFields_28.TabIndex = 28;
			this._txtFields_28.AcceptsReturn = true;
			this._txtFields_28.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_28.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_28.CausesValidation = true;
			this._txtFields_28.Enabled = true;
			this._txtFields_28.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_28.HideSelection = true;
			this._txtFields_28.ReadOnly = false;
			this._txtFields_28.MaxLength = 0;
			this._txtFields_28.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_28.Multiline = false;
			this._txtFields_28.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_28.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_28.TabStop = true;
			this._txtFields_28.Visible = true;
			this._txtFields_28.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_28.Name = "_txtFields_28";
			this._txtFields_27.AutoSize = false;
			this._txtFields_27.Size = new System.Drawing.Size(168, 19);
			this._txtFields_27.Location = new System.Drawing.Point(476, 86);
			this._txtFields_27.TabIndex = 30;
			this._txtFields_27.AcceptsReturn = true;
			this._txtFields_27.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_27.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_27.CausesValidation = true;
			this._txtFields_27.Enabled = true;
			this._txtFields_27.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_27.HideSelection = true;
			this._txtFields_27.ReadOnly = false;
			this._txtFields_27.MaxLength = 0;
			this._txtFields_27.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_27.Multiline = false;
			this._txtFields_27.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_27.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_27.TabStop = true;
			this._txtFields_27.Visible = true;
			this._txtFields_27.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_27.Name = "_txtFields_27";
			this._txtFields_26.AutoSize = false;
			this._txtFields_26.Size = new System.Drawing.Size(168, 19);
			this._txtFields_26.Location = new System.Drawing.Point(476, 108);
			this._txtFields_26.TabIndex = 32;
			this._txtFields_26.AcceptsReturn = true;
			this._txtFields_26.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_26.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_26.CausesValidation = true;
			this._txtFields_26.Enabled = true;
			this._txtFields_26.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_26.HideSelection = true;
			this._txtFields_26.ReadOnly = false;
			this._txtFields_26.MaxLength = 0;
			this._txtFields_26.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_26.Multiline = false;
			this._txtFields_26.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_26.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_26.TabStop = true;
			this._txtFields_26.Visible = true;
			this._txtFields_26.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_26.Name = "_txtFields_26";
			this._txtFields_1.AutoSize = false;
			this._txtFields_1.Size = new System.Drawing.Size(291, 19);
			this._txtFields_1.Location = new System.Drawing.Point(353, 146);
			this._txtFields_1.TabIndex = 34;
			this._txtFields_1.AcceptsReturn = true;
			this._txtFields_1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_1.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_1.CausesValidation = true;
			this._txtFields_1.Enabled = true;
			this._txtFields_1.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_1.HideSelection = true;
			this._txtFields_1.ReadOnly = false;
			this._txtFields_1.MaxLength = 0;
			this._txtFields_1.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_1.Multiline = false;
			this._txtFields_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_1.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_1.TabStop = true;
			this._txtFields_1.Visible = true;
			this._txtFields_1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_1.Name = "_txtFields_1";
			this._txtFloatNegative_11.AutoSize = false;
			this._txtFloatNegative_11.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_11.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_11.Location = new System.Drawing.Point(434, 223);
			this._txtFloatNegative_11.TabIndex = 37;
			this._txtFloatNegative_11.AcceptsReturn = true;
			this._txtFloatNegative_11.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_11.CausesValidation = true;
			this._txtFloatNegative_11.Enabled = true;
			this._txtFloatNegative_11.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_11.HideSelection = true;
			this._txtFloatNegative_11.ReadOnly = false;
			this._txtFloatNegative_11.MaxLength = 0;
			this._txtFloatNegative_11.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_11.Multiline = false;
			this._txtFloatNegative_11.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_11.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_11.TabStop = true;
			this._txtFloatNegative_11.Visible = true;
			this._txtFloatNegative_11.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_11.Name = "_txtFloatNegative_11";
			this._txtFloatNegative_12.AutoSize = false;
			this._txtFloatNegative_12.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_12.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_12.Location = new System.Drawing.Point(434, 244);
			this._txtFloatNegative_12.TabIndex = 39;
			this._txtFloatNegative_12.AcceptsReturn = true;
			this._txtFloatNegative_12.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_12.CausesValidation = true;
			this._txtFloatNegative_12.Enabled = true;
			this._txtFloatNegative_12.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_12.HideSelection = true;
			this._txtFloatNegative_12.ReadOnly = false;
			this._txtFloatNegative_12.MaxLength = 0;
			this._txtFloatNegative_12.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_12.Multiline = false;
			this._txtFloatNegative_12.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_12.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_12.TabStop = true;
			this._txtFloatNegative_12.Visible = true;
			this._txtFloatNegative_12.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_12.Name = "_txtFloatNegative_12";
			this._txtFloatNegative_13.AutoSize = false;
			this._txtFloatNegative_13.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_13.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_13.Location = new System.Drawing.Point(572, 244);
			this._txtFloatNegative_13.TabIndex = 41;
			this._txtFloatNegative_13.AcceptsReturn = true;
			this._txtFloatNegative_13.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_13.CausesValidation = true;
			this._txtFloatNegative_13.Enabled = true;
			this._txtFloatNegative_13.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_13.HideSelection = true;
			this._txtFloatNegative_13.ReadOnly = false;
			this._txtFloatNegative_13.MaxLength = 0;
			this._txtFloatNegative_13.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_13.Multiline = false;
			this._txtFloatNegative_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_13.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_13.TabStop = true;
			this._txtFloatNegative_13.Visible = true;
			this._txtFloatNegative_13.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_13.Name = "_txtFloatNegative_13";
			this._txtFloatNegative_14.AutoSize = false;
			this._txtFloatNegative_14.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_14.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_14.Location = new System.Drawing.Point(434, 266);
			this._txtFloatNegative_14.TabIndex = 43;
			this._txtFloatNegative_14.AcceptsReturn = true;
			this._txtFloatNegative_14.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_14.CausesValidation = true;
			this._txtFloatNegative_14.Enabled = true;
			this._txtFloatNegative_14.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_14.HideSelection = true;
			this._txtFloatNegative_14.ReadOnly = false;
			this._txtFloatNegative_14.MaxLength = 0;
			this._txtFloatNegative_14.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_14.Multiline = false;
			this._txtFloatNegative_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_14.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_14.TabStop = true;
			this._txtFloatNegative_14.Visible = true;
			this._txtFloatNegative_14.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_14.Name = "_txtFloatNegative_14";
			this._txtFloatNegative_15.AutoSize = false;
			this._txtFloatNegative_15.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_15.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_15.Location = new System.Drawing.Point(572, 266);
			this._txtFloatNegative_15.TabIndex = 45;
			this._txtFloatNegative_15.AcceptsReturn = true;
			this._txtFloatNegative_15.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_15.CausesValidation = true;
			this._txtFloatNegative_15.Enabled = true;
			this._txtFloatNegative_15.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_15.HideSelection = true;
			this._txtFloatNegative_15.ReadOnly = false;
			this._txtFloatNegative_15.MaxLength = 0;
			this._txtFloatNegative_15.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_15.Multiline = false;
			this._txtFloatNegative_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_15.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_15.TabStop = true;
			this._txtFloatNegative_15.Visible = true;
			this._txtFloatNegative_15.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_15.Name = "_txtFloatNegative_15";
			this._txtFloatNegative_16.AutoSize = false;
			this._txtFloatNegative_16.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_16.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_16.Location = new System.Drawing.Point(434, 287);
			this._txtFloatNegative_16.TabIndex = 47;
			this._txtFloatNegative_16.AcceptsReturn = true;
			this._txtFloatNegative_16.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_16.CausesValidation = true;
			this._txtFloatNegative_16.Enabled = true;
			this._txtFloatNegative_16.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_16.HideSelection = true;
			this._txtFloatNegative_16.ReadOnly = false;
			this._txtFloatNegative_16.MaxLength = 0;
			this._txtFloatNegative_16.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_16.Multiline = false;
			this._txtFloatNegative_16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_16.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_16.TabStop = true;
			this._txtFloatNegative_16.Visible = true;
			this._txtFloatNegative_16.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_16.Name = "_txtFloatNegative_16";
			this._txtFloatNegative_17.AutoSize = false;
			this._txtFloatNegative_17.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_17.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_17.Location = new System.Drawing.Point(572, 288);
			this._txtFloatNegative_17.TabIndex = 49;
			this._txtFloatNegative_17.AcceptsReturn = true;
			this._txtFloatNegative_17.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_17.CausesValidation = true;
			this._txtFloatNegative_17.Enabled = true;
			this._txtFloatNegative_17.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_17.HideSelection = true;
			this._txtFloatNegative_17.ReadOnly = false;
			this._txtFloatNegative_17.MaxLength = 0;
			this._txtFloatNegative_17.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_17.Multiline = false;
			this._txtFloatNegative_17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_17.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_17.TabStop = true;
			this._txtFloatNegative_17.Visible = true;
			this._txtFloatNegative_17.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_17.Name = "_txtFloatNegative_17";
			this._txtFloatNegative_18.AutoSize = false;
			this._txtFloatNegative_18.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloatNegative_18.Size = new System.Drawing.Size(72, 19);
			this._txtFloatNegative_18.Location = new System.Drawing.Point(434, 309);
			this._txtFloatNegative_18.TabIndex = 51;
			this._txtFloatNegative_18.AcceptsReturn = true;
			this._txtFloatNegative_18.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloatNegative_18.CausesValidation = true;
			this._txtFloatNegative_18.Enabled = true;
			this._txtFloatNegative_18.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloatNegative_18.HideSelection = true;
			this._txtFloatNegative_18.ReadOnly = false;
			this._txtFloatNegative_18.MaxLength = 0;
			this._txtFloatNegative_18.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloatNegative_18.Multiline = false;
			this._txtFloatNegative_18.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloatNegative_18.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloatNegative_18.TabStop = true;
			this._txtFloatNegative_18.Visible = true;
			this._txtFloatNegative_18.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloatNegative_18.Name = "_txtFloatNegative_18";
			this._txtFields_2.AutoSize = false;
			this._txtFields_2.Size = new System.Drawing.Size(226, 19);
			this._txtFields_2.Location = new System.Drawing.Point(102, 63);
			this._txtFields_2.TabIndex = 2;
			this._txtFields_2.AcceptsReturn = true;
			this._txtFields_2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_2.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_2.CausesValidation = true;
			this._txtFields_2.Enabled = true;
			this._txtFields_2.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_2.HideSelection = true;
			this._txtFields_2.ReadOnly = false;
			this._txtFields_2.MaxLength = 0;
			this._txtFields_2.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_2.Multiline = false;
			this._txtFields_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_2.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_2.TabStop = true;
			this._txtFields_2.Visible = true;
			this._txtFields_2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_2.Name = "_txtFields_2";
			this._txtFields_6.AutoSize = false;
			this._txtFields_6.Size = new System.Drawing.Size(226, 49);
			this._txtFields_6.Location = new System.Drawing.Point(102, 108);
			this._txtFields_6.Multiline = true;
			this._txtFields_6.TabIndex = 9;
			this._txtFields_6.AcceptsReturn = true;
			this._txtFields_6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_6.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_6.CausesValidation = true;
			this._txtFields_6.Enabled = true;
			this._txtFields_6.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_6.HideSelection = true;
			this._txtFields_6.ReadOnly = false;
			this._txtFields_6.MaxLength = 0;
			this._txtFields_6.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_6.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_6.TabStop = true;
			this._txtFields_6.Visible = true;
			this._txtFields_6.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_6.Name = "_txtFields_6";
			this._txtFields_7.AutoSize = false;
			this._txtFields_7.Size = new System.Drawing.Size(226, 49);
			this._txtFields_7.Location = new System.Drawing.Point(102, 162);
			this._txtFields_7.Multiline = true;
			this._txtFields_7.TabIndex = 13;
			this._txtFields_7.AcceptsReturn = true;
			this._txtFields_7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_7.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_7.CausesValidation = true;
			this._txtFields_7.Enabled = true;
			this._txtFields_7.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_7.HideSelection = true;
			this._txtFields_7.ReadOnly = false;
			this._txtFields_7.MaxLength = 0;
			this._txtFields_7.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_7.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_7.TabStop = true;
			this._txtFields_7.Visible = true;
			this._txtFields_7.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_7.Name = "_txtFields_7";
			this._txtFields_8.AutoSize = false;
			this._txtFields_8.Size = new System.Drawing.Size(94, 19);
			this._txtFields_8.Location = new System.Drawing.Point(102, 84);
			this._txtFields_8.TabIndex = 4;
			this._txtFields_8.AcceptsReturn = true;
			this._txtFields_8.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_8.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_8.CausesValidation = true;
			this._txtFields_8.Enabled = true;
			this._txtFields_8.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_8.HideSelection = true;
			this._txtFields_8.ReadOnly = false;
			this._txtFields_8.MaxLength = 0;
			this._txtFields_8.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_8.Multiline = false;
			this._txtFields_8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_8.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_8.TabStop = true;
			this._txtFields_8.Visible = true;
			this._txtFields_8.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_8.Name = "_txtFields_8";
			this._txtFields_9.AutoSize = false;
			this._txtFields_9.Size = new System.Drawing.Size(94, 19);
			this._txtFields_9.Location = new System.Drawing.Point(234, 84);
			this._txtFields_9.TabIndex = 6;
			this._txtFields_9.AcceptsReturn = true;
			this._txtFields_9.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this._txtFields_9.BackColor = System.Drawing.SystemColors.Window;
			this._txtFields_9.CausesValidation = true;
			this._txtFields_9.Enabled = true;
			this._txtFields_9.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFields_9.HideSelection = true;
			this._txtFields_9.ReadOnly = false;
			this._txtFields_9.MaxLength = 0;
			this._txtFields_9.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFields_9.Multiline = false;
			this._txtFields_9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFields_9.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFields_9.TabStop = true;
			this._txtFields_9.Visible = true;
			this._txtFields_9.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFields_9.Name = "_txtFields_9";
			this._txtFloat_13.AutoSize = false;
			this._txtFloat_13.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloat_13.Enabled = false;
			this._txtFloat_13.Size = new System.Drawing.Size(91, 19);
			this._txtFloat_13.Location = new System.Drawing.Point(84, 261);
			this._txtFloat_13.TabIndex = 17;
			this._txtFloat_13.AcceptsReturn = true;
			this._txtFloat_13.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloat_13.CausesValidation = true;
			this._txtFloat_13.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloat_13.HideSelection = true;
			this._txtFloat_13.ReadOnly = false;
			this._txtFloat_13.MaxLength = 0;
			this._txtFloat_13.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloat_13.Multiline = false;
			this._txtFloat_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloat_13.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloat_13.TabStop = true;
			this._txtFloat_13.Visible = true;
			this._txtFloat_13.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloat_13.Name = "_txtFloat_13";
			this._txtFloat_14.AutoSize = false;
			this._txtFloat_14.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloat_14.Enabled = false;
			this._txtFloat_14.Size = new System.Drawing.Size(91, 19);
			this._txtFloat_14.Location = new System.Drawing.Point(237, 261);
			this._txtFloat_14.TabIndex = 19;
			this._txtFloat_14.AcceptsReturn = true;
			this._txtFloat_14.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloat_14.CausesValidation = true;
			this._txtFloat_14.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloat_14.HideSelection = true;
			this._txtFloat_14.ReadOnly = false;
			this._txtFloat_14.MaxLength = 0;
			this._txtFloat_14.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloat_14.Multiline = false;
			this._txtFloat_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloat_14.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloat_14.TabStop = true;
			this._txtFloat_14.Visible = true;
			this._txtFloat_14.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloat_14.Name = "_txtFloat_14";
			this._txtFloat_15.AutoSize = false;
			this._txtFloat_15.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloat_15.Enabled = false;
			this._txtFloat_15.Size = new System.Drawing.Size(91, 19);
			this._txtFloat_15.Location = new System.Drawing.Point(84, 282);
			this._txtFloat_15.TabIndex = 21;
			this._txtFloat_15.AcceptsReturn = true;
			this._txtFloat_15.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloat_15.CausesValidation = true;
			this._txtFloat_15.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloat_15.HideSelection = true;
			this._txtFloat_15.ReadOnly = false;
			this._txtFloat_15.MaxLength = 0;
			this._txtFloat_15.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloat_15.Multiline = false;
			this._txtFloat_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloat_15.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloat_15.TabStop = true;
			this._txtFloat_15.Visible = true;
			this._txtFloat_15.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloat_15.Name = "_txtFloat_15";
			this._txtFloat_16.AutoSize = false;
			this._txtFloat_16.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloat_16.Enabled = false;
			this._txtFloat_16.Size = new System.Drawing.Size(91, 19);
			this._txtFloat_16.Location = new System.Drawing.Point(237, 282);
			this._txtFloat_16.TabIndex = 23;
			this._txtFloat_16.AcceptsReturn = true;
			this._txtFloat_16.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloat_16.CausesValidation = true;
			this._txtFloat_16.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloat_16.HideSelection = true;
			this._txtFloat_16.ReadOnly = false;
			this._txtFloat_16.MaxLength = 0;
			this._txtFloat_16.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloat_16.Multiline = false;
			this._txtFloat_16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloat_16.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloat_16.TabStop = true;
			this._txtFloat_16.Visible = true;
			this._txtFloat_16.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloat_16.Name = "_txtFloat_16";
			this._txtFloat_17.AutoSize = false;
			this._txtFloat_17.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._txtFloat_17.Enabled = false;
			this._txtFloat_17.Size = new System.Drawing.Size(91, 19);
			this._txtFloat_17.Location = new System.Drawing.Point(84, 303);
			this._txtFloat_17.TabIndex = 25;
			this._txtFloat_17.AcceptsReturn = true;
			this._txtFloat_17.BackColor = System.Drawing.SystemColors.Window;
			this._txtFloat_17.CausesValidation = true;
			this._txtFloat_17.ForeColor = System.Drawing.SystemColors.WindowText;
			this._txtFloat_17.HideSelection = true;
			this._txtFloat_17.ReadOnly = false;
			this._txtFloat_17.MaxLength = 0;
			this._txtFloat_17.Cursor = System.Windows.Forms.Cursors.IBeam;
			this._txtFloat_17.Multiline = false;
			this._txtFloat_17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._txtFloat_17.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this._txtFloat_17.TabStop = true;
			this._txtFloat_17.Visible = true;
			this._txtFloat_17.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this._txtFloat_17.Name = "_txtFloat_17";
			this.picButtons.Dock = System.Windows.Forms.DockStyle.Top;
			this.picButtons.BackColor = System.Drawing.Color.Blue;
			this.picButtons.Size = new System.Drawing.Size(661, 38);
			this.picButtons.Location = new System.Drawing.Point(0, 0);
			this.picButtons.TabIndex = 12;
			this.picButtons.TabStop = false;
			this.picButtons.CausesValidation = true;
			this.picButtons.Enabled = true;
			this.picButtons.ForeColor = System.Drawing.SystemColors.ControlText;
			this.picButtons.Cursor = System.Windows.Forms.Cursors.Default;
			this.picButtons.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.picButtons.Visible = true;
			this.picButtons.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.picButtons.Name = "picButtons";
			this.cmdStatement.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdStatement.Text = "Statement";
			this.cmdStatement.Size = new System.Drawing.Size(103, 29);
			this.cmdStatement.Location = new System.Drawing.Point(232, 2);
			this.cmdStatement.TabIndex = 52;
			this.cmdStatement.BackColor = System.Drawing.SystemColors.Control;
			this.cmdStatement.CausesValidation = true;
			this.cmdStatement.Enabled = true;
			this.cmdStatement.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdStatement.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdStatement.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdStatement.TabStop = true;
			this.cmdStatement.Name = "cmdStatement";
			this.cmdCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdCancel.Text = "&Undo";
			this.cmdCancel.Size = new System.Drawing.Size(73, 29);
			this.cmdCancel.Location = new System.Drawing.Point(5, 3);
			this.cmdCancel.TabIndex = 10;
			this.cmdCancel.TabStop = false;
			this.cmdCancel.BackColor = System.Drawing.SystemColors.Control;
			this.cmdCancel.CausesValidation = true;
			this.cmdCancel.Enabled = true;
			this.cmdCancel.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdCancel.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdCancel.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdClose.Text = "E&xit";
			this.cmdClose.Size = new System.Drawing.Size(73, 29);
			this.cmdClose.Location = new System.Drawing.Point(576, 3);
			this.cmdClose.TabIndex = 8;
			this.cmdClose.TabStop = false;
			this.cmdClose.BackColor = System.Drawing.SystemColors.Control;
			this.cmdClose.CausesValidation = true;
			this.cmdClose.Enabled = true;
			this.cmdClose.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdClose.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdClose.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdClose.Name = "cmdClose";
			//cmbTemplate.OcxState = CType(resources.GetObject("cmbTemplate.OcxState"), System.Windows.Forms.AxHost.State)
			this.cmbTemplate.Size = new System.Drawing.Size(212, 21);
			this.cmbTemplate.Location = new System.Drawing.Point(432, 168);
			this.cmbTemplate.TabIndex = 54;
			this.cmbTemplate.Name = "cmbTemplate";
			this._lbl_4.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lbl_4.Text = "GRV Template :";
			this._lbl_4.Size = new System.Drawing.Size(76, 13);
			this._lbl_4.Location = new System.Drawing.Point(350, 171);
			this._lbl_4.TabIndex = 53;
			this._lbl_4.BackColor = System.Drawing.Color.Transparent;
			this._lbl_4.Enabled = true;
			this._lbl_4.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lbl_4.Cursor = System.Windows.Forms.Cursors.Default;
			this._lbl_4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lbl_4.UseMnemonic = true;
			this._lbl_4.Visible = true;
			this._lbl_4.AutoSize = true;
			this._lbl_4.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lbl_4.Name = "_lbl_4";
			this._lbl_3.BackColor = System.Drawing.Color.Transparent;
			this._lbl_3.Text = "&3. Payment Terms";
			this._lbl_3.Size = new System.Drawing.Size(102, 13);
			this._lbl_3.Location = new System.Drawing.Point(345, 201);
			this._lbl_3.TabIndex = 35;
			this._lbl_3.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._lbl_3.Enabled = true;
			this._lbl_3.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lbl_3.Cursor = System.Windows.Forms.Cursors.Default;
			this._lbl_3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lbl_3.UseMnemonic = true;
			this._lbl_3.Visible = true;
			this._lbl_3.AutoSize = true;
			this._lbl_3.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lbl_3.Name = "_lbl_3";
			this._lbl_2.BackColor = System.Drawing.Color.Transparent;
			this._lbl_2.Text = "&2. Ordering Details";
			this._lbl_2.Size = new System.Drawing.Size(107, 13);
			this._lbl_2.Location = new System.Drawing.Point(345, 42);
			this._lbl_2.TabIndex = 26;
			this._lbl_2.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._lbl_2.Enabled = true;
			this._lbl_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lbl_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._lbl_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lbl_2.UseMnemonic = true;
			this._lbl_2.Visible = true;
			this._lbl_2.AutoSize = true;
			this._lbl_2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lbl_2.Name = "_lbl_2";
			this._lblLabels_38.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_38.Text = "Representative Name:";
			this._lblLabels_38.Size = new System.Drawing.Size(106, 13);
			this._lblLabels_38.Location = new System.Drawing.Point(363, 65);
			this._lblLabels_38.TabIndex = 27;
			this._lblLabels_38.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_38.Enabled = true;
			this._lblLabels_38.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_38.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_38.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_38.UseMnemonic = true;
			this._lblLabels_38.Visible = true;
			this._lblLabels_38.AutoSize = true;
			this._lblLabels_38.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_38.Name = "_lblLabels_38";
			this._lblLabels_37.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_37.Text = "Representative Number:";
			this._lblLabels_37.Size = new System.Drawing.Size(115, 13);
			this._lblLabels_37.Location = new System.Drawing.Point(354, 86);
			this._lblLabels_37.TabIndex = 29;
			this._lblLabels_37.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_37.Enabled = true;
			this._lblLabels_37.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_37.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_37.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_37.UseMnemonic = true;
			this._lblLabels_37.Visible = true;
			this._lblLabels_37.AutoSize = true;
			this._lblLabels_37.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_37.Name = "_lblLabels_37";
			this._lblLabels_36.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_36.Text = "Account Number:";
			this._lblLabels_36.Size = new System.Drawing.Size(83, 13);
			this._lblLabels_36.Location = new System.Drawing.Point(386, 108);
			this._lblLabels_36.TabIndex = 31;
			this._lblLabels_36.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_36.Enabled = true;
			this._lblLabels_36.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_36.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_36.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_36.UseMnemonic = true;
			this._lblLabels_36.Visible = true;
			this._lblLabels_36.AutoSize = true;
			this._lblLabels_36.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_36.Name = "_lblLabels_36";
			this._lblLabels_35.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_35.Text = "Default Order Attention Line text:";
			this._lblLabels_35.Size = new System.Drawing.Size(154, 13);
			this._lblLabels_35.Location = new System.Drawing.Point(357, 129);
			this._lblLabels_35.TabIndex = 33;
			this._lblLabels_35.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_35.Enabled = true;
			this._lblLabels_35.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_35.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_35.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_35.UseMnemonic = true;
			this._lblLabels_35.Visible = true;
			this._lblLabels_35.AutoSize = true;
			this._lblLabels_35.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_35.Name = "_lblLabels_35";
			this._lblLabels_33.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_33.Text = "Ullage Discount:";
			this._lblLabels_33.Size = new System.Drawing.Size(78, 13);
			this._lblLabels_33.Location = new System.Drawing.Point(349, 223);
			this._lblLabels_33.TabIndex = 36;
			this._lblLabels_33.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_33.Enabled = true;
			this._lblLabels_33.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_33.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_33.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_33.UseMnemonic = true;
			this._lblLabels_33.Visible = true;
			this._lblLabels_33.AutoSize = true;
			this._lblLabels_33.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_33.Name = "_lblLabels_33";
			this._lblLabels_32.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_32.Text = "C.O.D.:";
			this._lblLabels_32.Size = new System.Drawing.Size(35, 13);
			this._lblLabels_32.Location = new System.Drawing.Point(392, 244);
			this._lblLabels_32.TabIndex = 38;
			this._lblLabels_32.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_32.Enabled = true;
			this._lblLabels_32.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_32.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_32.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_32.UseMnemonic = true;
			this._lblLabels_32.Visible = true;
			this._lblLabels_32.AutoSize = true;
			this._lblLabels_32.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_32.Name = "_lblLabels_32";
			this._lblLabels_31.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_31.Text = "15 days:";
			this._lblLabels_31.Size = new System.Drawing.Size(40, 13);
			this._lblLabels_31.Location = new System.Drawing.Point(525, 244);
			this._lblLabels_31.TabIndex = 40;
			this._lblLabels_31.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_31.Enabled = true;
			this._lblLabels_31.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_31.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_31.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_31.UseMnemonic = true;
			this._lblLabels_31.Visible = true;
			this._lblLabels_31.AutoSize = true;
			this._lblLabels_31.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_31.Name = "_lblLabels_31";
			this._lblLabels_30.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_30.Text = "30 days:";
			this._lblLabels_30.Size = new System.Drawing.Size(40, 13);
			this._lblLabels_30.Location = new System.Drawing.Point(387, 266);
			this._lblLabels_30.TabIndex = 42;
			this._lblLabels_30.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_30.Enabled = true;
			this._lblLabels_30.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_30.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_30.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_30.UseMnemonic = true;
			this._lblLabels_30.Visible = true;
			this._lblLabels_30.AutoSize = true;
			this._lblLabels_30.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_30.Name = "_lblLabels_30";
			this._lblLabels_29.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_29.Text = "60 days:";
			this._lblLabels_29.Size = new System.Drawing.Size(40, 13);
			this._lblLabels_29.Location = new System.Drawing.Point(525, 266);
			this._lblLabels_29.TabIndex = 44;
			this._lblLabels_29.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_29.Enabled = true;
			this._lblLabels_29.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_29.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_29.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_29.UseMnemonic = true;
			this._lblLabels_29.Visible = true;
			this._lblLabels_29.AutoSize = true;
			this._lblLabels_29.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_29.Name = "_lblLabels_29";
			this._lblLabels_28.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_28.Text = "90 days:";
			this._lblLabels_28.Size = new System.Drawing.Size(40, 13);
			this._lblLabels_28.Location = new System.Drawing.Point(387, 287);
			this._lblLabels_28.TabIndex = 46;
			this._lblLabels_28.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_28.Enabled = true;
			this._lblLabels_28.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_28.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_28.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_28.UseMnemonic = true;
			this._lblLabels_28.Visible = true;
			this._lblLabels_28.AutoSize = true;
			this._lblLabels_28.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_28.Name = "_lblLabels_28";
			this._lblLabels_27.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_27.Text = "120 days:";
			this._lblLabels_27.Size = new System.Drawing.Size(46, 13);
			this._lblLabels_27.Location = new System.Drawing.Point(519, 288);
			this._lblLabels_27.TabIndex = 48;
			this._lblLabels_27.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_27.Enabled = true;
			this._lblLabels_27.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_27.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_27.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_27.UseMnemonic = true;
			this._lblLabels_27.Visible = true;
			this._lblLabels_27.AutoSize = true;
			this._lblLabels_27.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_27.Name = "_lblLabels_27";
			this._lblLabels_26.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_26.Text = "Smart Card:";
			this._lblLabels_26.Size = new System.Drawing.Size(55, 13);
			this._lblLabels_26.Location = new System.Drawing.Point(372, 309);
			this._lblLabels_26.TabIndex = 50;
			this._lblLabels_26.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_26.Enabled = true;
			this._lblLabels_26.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_26.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_26.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_26.UseMnemonic = true;
			this._lblLabels_26.Visible = true;
			this._lblLabels_26.AutoSize = true;
			this._lblLabels_26.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_26.Name = "_lblLabels_26";
			this._lbl_1.BackColor = System.Drawing.Color.Transparent;
			this._lbl_1.Text = "&1. General";
			this._lbl_1.Size = new System.Drawing.Size(61, 13);
			this._lbl_1.Location = new System.Drawing.Point(6, 42);
			this._lbl_1.TabIndex = 0;
			this._lbl_1.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._lbl_1.Enabled = true;
			this._lbl_1.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lbl_1.Cursor = System.Windows.Forms.Cursors.Default;
			this._lbl_1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lbl_1.UseMnemonic = true;
			this._lbl_1.Visible = true;
			this._lbl_1.AutoSize = true;
			this._lbl_1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lbl_1.Name = "_lbl_1";
			this._lbl_0.BackColor = System.Drawing.Color.Transparent;
			this._lbl_0.Text = "Aging";
			this._lbl_0.Size = new System.Drawing.Size(33, 13);
			this._lbl_0.Location = new System.Drawing.Point(6, 240);
			this._lbl_0.TabIndex = 14;
			this._lbl_0.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this._lbl_0.Enabled = true;
			this._lbl_0.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lbl_0.Cursor = System.Windows.Forms.Cursors.Default;
			this._lbl_0.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lbl_0.UseMnemonic = true;
			this._lbl_0.Visible = true;
			this._lbl_0.AutoSize = true;
			this._lbl_0.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lbl_0.Name = "_lbl_0";
			this._lblLabels_2.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_2.Text = "Supplier Name:";
			this._lblLabels_2.Size = new System.Drawing.Size(87, 13);
			this._lblLabels_2.Location = new System.Drawing.Point(10, 63);
			this._lblLabels_2.TabIndex = 1;
			this._lblLabels_2.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_2.Enabled = true;
			this._lblLabels_2.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_2.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_2.UseMnemonic = true;
			this._lblLabels_2.Visible = true;
			this._lblLabels_2.AutoSize = true;
			this._lblLabels_2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_2.Name = "_lblLabels_2";
			this._lblLabels_6.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_6.Text = "Physical Address:";
			this._lblLabels_6.Size = new System.Drawing.Size(83, 13);
			this._lblLabels_6.Location = new System.Drawing.Point(14, 108);
			this._lblLabels_6.TabIndex = 7;
			this._lblLabels_6.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_6.Enabled = true;
			this._lblLabels_6.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_6.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_6.UseMnemonic = true;
			this._lblLabels_6.Visible = true;
			this._lblLabels_6.AutoSize = true;
			this._lblLabels_6.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_6.Name = "_lblLabels_6";
			this._lblLabels_7.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_7.Text = "Postal Address:";
			this._lblLabels_7.Size = new System.Drawing.Size(76, 13);
			this._lblLabels_7.Location = new System.Drawing.Point(21, 159);
			this._lblLabels_7.TabIndex = 11;
			this._lblLabels_7.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_7.Enabled = true;
			this._lblLabels_7.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_7.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_7.UseMnemonic = true;
			this._lblLabels_7.Visible = true;
			this._lblLabels_7.AutoSize = true;
			this._lblLabels_7.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_7.Name = "_lblLabels_7";
			this._lblLabels_8.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_8.Text = "Telephone:";
			this._lblLabels_8.Size = new System.Drawing.Size(55, 13);
			this._lblLabels_8.Location = new System.Drawing.Point(39, 84);
			this._lblLabels_8.TabIndex = 3;
			this._lblLabels_8.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_8.Enabled = true;
			this._lblLabels_8.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_8.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_8.UseMnemonic = true;
			this._lblLabels_8.Visible = true;
			this._lblLabels_8.AutoSize = true;
			this._lblLabels_8.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_8.Name = "_lblLabels_8";
			this._lblLabels_9.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_9.Text = "Fax:";
			this._lblLabels_9.Size = new System.Drawing.Size(22, 13);
			this._lblLabels_9.Location = new System.Drawing.Point(207, 84);
			this._lblLabels_9.TabIndex = 5;
			this._lblLabels_9.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_9.Enabled = true;
			this._lblLabels_9.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_9.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_9.UseMnemonic = true;
			this._lblLabels_9.Visible = true;
			this._lblLabels_9.AutoSize = true;
			this._lblLabels_9.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_9.Name = "_lblLabels_9";
			this._lblLabels_13.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_13.Text = "Current:";
			this._lblLabels_13.Size = new System.Drawing.Size(37, 13);
			this._lblLabels_13.Location = new System.Drawing.Point(36, 264);
			this._lblLabels_13.TabIndex = 16;
			this._lblLabels_13.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_13.Enabled = true;
			this._lblLabels_13.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_13.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_13.UseMnemonic = true;
			this._lblLabels_13.Visible = true;
			this._lblLabels_13.AutoSize = true;
			this._lblLabels_13.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_13.Name = "_lblLabels_13";
			this._lblLabels_14.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_14.Text = "30 Days:";
			this._lblLabels_14.Size = new System.Drawing.Size(43, 13);
			this._lblLabels_14.Location = new System.Drawing.Point(189, 261);
			this._lblLabels_14.TabIndex = 18;
			this._lblLabels_14.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_14.Enabled = true;
			this._lblLabels_14.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_14.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_14.UseMnemonic = true;
			this._lblLabels_14.Visible = true;
			this._lblLabels_14.AutoSize = true;
			this._lblLabels_14.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_14.Name = "_lblLabels_14";
			this._lblLabels_15.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_15.Text = "60 Days:";
			this._lblLabels_15.Size = new System.Drawing.Size(43, 13);
			this._lblLabels_15.Location = new System.Drawing.Point(30, 285);
			this._lblLabels_15.TabIndex = 20;
			this._lblLabels_15.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_15.Enabled = true;
			this._lblLabels_15.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_15.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_15.UseMnemonic = true;
			this._lblLabels_15.Visible = true;
			this._lblLabels_15.AutoSize = true;
			this._lblLabels_15.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_15.Name = "_lblLabels_15";
			this._lblLabels_16.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_16.Text = "90 Days:";
			this._lblLabels_16.Size = new System.Drawing.Size(43, 13);
			this._lblLabels_16.Location = new System.Drawing.Point(189, 282);
			this._lblLabels_16.TabIndex = 22;
			this._lblLabels_16.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_16.Enabled = true;
			this._lblLabels_16.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_16.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_16.UseMnemonic = true;
			this._lblLabels_16.Visible = true;
			this._lblLabels_16.AutoSize = true;
			this._lblLabels_16.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_16.Name = "_lblLabels_16";
			this._lblLabels_17.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this._lblLabels_17.Text = "120 Days:";
			this._lblLabels_17.Size = new System.Drawing.Size(49, 13);
			this._lblLabels_17.Location = new System.Drawing.Point(24, 306);
			this._lblLabels_17.TabIndex = 24;
			this._lblLabels_17.BackColor = System.Drawing.Color.Transparent;
			this._lblLabels_17.Enabled = true;
			this._lblLabels_17.ForeColor = System.Drawing.SystemColors.ControlText;
			this._lblLabels_17.Cursor = System.Windows.Forms.Cursors.Default;
			this._lblLabels_17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this._lblLabels_17.UseMnemonic = true;
			this._lblLabels_17.Visible = true;
			this._lblLabels_17.AutoSize = true;
			this._lblLabels_17.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this._lblLabels_17.Name = "_lblLabels_17";
			this._Shape1_0.BackColor = System.Drawing.Color.FromArgb(192, 192, 255);
			this._Shape1_0.BackStyle = Microsoft.VisualBasic.PowerPacks.BackStyle.Opaque;
			this._Shape1_0.Size = new System.Drawing.Size(328, 76);
			this._Shape1_0.Location = new System.Drawing.Point(6, 255);
			this._Shape1_0.BorderColor = System.Drawing.SystemColors.WindowText;
			this._Shape1_0.BorderStyle = System.Drawing.Drawing2D.DashStyle.Solid;
			this._Shape1_0.BorderWidth = 1;
			this._Shape1_0.FillColor = System.Drawing.Color.Black;
			this._Shape1_0.FillStyle = Microsoft.VisualBasic.PowerPacks.FillStyle.Transparent;
			this._Shape1_0.Visible = true;
			this._Shape1_0.Name = "_Shape1_0";
			this._Shape1_1.BackColor = System.Drawing.Color.FromArgb(192, 192, 255);
			this._Shape1_1.BackStyle = Microsoft.VisualBasic.PowerPacks.BackStyle.Opaque;
			this._Shape1_1.Size = new System.Drawing.Size(328, 181);
			this._Shape1_1.Location = new System.Drawing.Point(6, 57);
			this._Shape1_1.BorderColor = System.Drawing.SystemColors.WindowText;
			this._Shape1_1.BorderStyle = System.Drawing.Drawing2D.DashStyle.Solid;
			this._Shape1_1.BorderWidth = 1;
			this._Shape1_1.FillColor = System.Drawing.Color.Black;
			this._Shape1_1.FillStyle = Microsoft.VisualBasic.PowerPacks.FillStyle.Transparent;
			this._Shape1_1.Visible = true;
			this._Shape1_1.Name = "_Shape1_1";
			this._Shape1_2.BackColor = System.Drawing.Color.FromArgb(192, 192, 255);
			this._Shape1_2.BackStyle = Microsoft.VisualBasic.PowerPacks.BackStyle.Opaque;
			this._Shape1_2.Size = new System.Drawing.Size(304, 140);
			this._Shape1_2.Location = new System.Drawing.Point(345, 57);
			this._Shape1_2.BorderColor = System.Drawing.SystemColors.WindowText;
			this._Shape1_2.BorderStyle = System.Drawing.Drawing2D.DashStyle.Solid;
			this._Shape1_2.BorderWidth = 1;
			this._Shape1_2.FillColor = System.Drawing.Color.Black;
			this._Shape1_2.FillStyle = Microsoft.VisualBasic.PowerPacks.FillStyle.Transparent;
			this._Shape1_2.Visible = true;
			this._Shape1_2.Name = "_Shape1_2";
			this._Shape1_3.BackColor = System.Drawing.Color.FromArgb(192, 192, 255);
			this._Shape1_3.BackStyle = Microsoft.VisualBasic.PowerPacks.BackStyle.Opaque;
			this._Shape1_3.Size = new System.Drawing.Size(304, 118);
			this._Shape1_3.Location = new System.Drawing.Point(345, 216);
			this._Shape1_3.BorderColor = System.Drawing.SystemColors.WindowText;
			this._Shape1_3.BorderStyle = System.Drawing.Drawing2D.DashStyle.Solid;
			this._Shape1_3.BorderWidth = 1;
			this._Shape1_3.FillColor = System.Drawing.Color.Black;
			this._Shape1_3.FillStyle = Microsoft.VisualBasic.PowerPacks.FillStyle.Transparent;
			this._Shape1_3.Visible = true;
			this._Shape1_3.Name = "_Shape1_3";
			this.Controls.Add(_chkFields_1);
			this.Controls.Add(_txtFields_28);
			this.Controls.Add(_txtFields_27);
			this.Controls.Add(_txtFields_26);
			this.Controls.Add(_txtFields_1);
			this.Controls.Add(_txtFloatNegative_11);
			this.Controls.Add(_txtFloatNegative_12);
			this.Controls.Add(_txtFloatNegative_13);
			this.Controls.Add(_txtFloatNegative_14);
			this.Controls.Add(_txtFloatNegative_15);
			this.Controls.Add(_txtFloatNegative_16);
			this.Controls.Add(_txtFloatNegative_17);
			this.Controls.Add(_txtFloatNegative_18);
			this.Controls.Add(_txtFields_2);
			this.Controls.Add(_txtFields_6);
			this.Controls.Add(_txtFields_7);
			this.Controls.Add(_txtFields_8);
			this.Controls.Add(_txtFields_9);
			this.Controls.Add(_txtFloat_13);
			this.Controls.Add(_txtFloat_14);
			this.Controls.Add(_txtFloat_15);
			this.Controls.Add(_txtFloat_16);
			this.Controls.Add(_txtFloat_17);
			this.Controls.Add(picButtons);
			this.Controls.Add(cmbTemplate);
			this.Controls.Add(_lbl_4);
			this.Controls.Add(_lbl_3);
			this.Controls.Add(_lbl_2);
			this.Controls.Add(_lblLabels_38);
			this.Controls.Add(_lblLabels_37);
			this.Controls.Add(_lblLabels_36);
			this.Controls.Add(_lblLabels_35);
			this.Controls.Add(_lblLabels_33);
			this.Controls.Add(_lblLabels_32);
			this.Controls.Add(_lblLabels_31);
			this.Controls.Add(_lblLabels_30);
			this.Controls.Add(_lblLabels_29);
			this.Controls.Add(_lblLabels_28);
			this.Controls.Add(_lblLabels_27);
			this.Controls.Add(_lblLabels_26);
			this.Controls.Add(_lbl_1);
			this.Controls.Add(_lbl_0);
			this.Controls.Add(_lblLabels_2);
			this.Controls.Add(_lblLabels_6);
			this.Controls.Add(_lblLabels_7);
			this.Controls.Add(_lblLabels_8);
			this.Controls.Add(_lblLabels_9);
			this.Controls.Add(_lblLabels_13);
			this.Controls.Add(_lblLabels_14);
			this.Controls.Add(_lblLabels_15);
			this.Controls.Add(_lblLabels_16);
			this.Controls.Add(_lblLabels_17);
			this.ShapeContainer1.Shapes.Add(_Shape1_0);
			this.ShapeContainer1.Shapes.Add(_Shape1_1);
			this.ShapeContainer1.Shapes.Add(_Shape1_2);
			this.ShapeContainer1.Shapes.Add(_Shape1_3);
			this.Controls.Add(ShapeContainer1);
			this.picButtons.Controls.Add(cmdStatement);
			this.picButtons.Controls.Add(cmdCancel);
			this.picButtons.Controls.Add(cmdClose);
			//Me.chkFields.SetIndex(_chkFields_1, CType(1, Short))
			//Me.lbl.SetIndex(_lbl_4, CType(4, Short))
			//Me.lbl.SetIndex(_lbl_3, CType(3, Short))
			//Me.lbl.SetIndex(_lbl_2, CType(2, Short))
			//Me.lbl.SetIndex(_lbl_1, CType(1, Short))
			//Me.lbl.SetIndex(_lbl_0, CType(0, Short))
			//Me.lblLabels.SetIndex(_lblLabels_38, CType(38, Short))
			//Me.lblLabels.SetIndex(_lblLabels_37, CType(37, Short))
			//Me.lblLabels.SetIndex(_lblLabels_36, CType(36, Short))
			//Me.lblLabels.SetIndex(_lblLabels_35, CType(35, Short))
			//Me.lblLabels.SetIndex(_lblLabels_33, CType(33, Short))
			//Me.lblLabels.SetIndex(_lblLabels_32, CType(32, Short))
			//Me.lblLabels.SetIndex(_lblLabels_31, CType(31, Short))
			//Me.lblLabels.SetIndex(_lblLabels_30, CType(30, Short))
			//Me.lblLabels.SetIndex(_lblLabels_29, CType(29, Short))
			//Me.lblLabels.SetIndex(_lblLabels_28, CType(28, Short))
			//Me.lblLabels.SetIndex(_lblLabels_27, CType(27, Short))
			//Me.lblLabels.SetIndex(_lblLabels_26, CType(26, Short))
			//Me.lblLabels.SetIndex(_lblLabels_2, CType(2, Short))
			//Me.lblLabels.SetIndex(_lblLabels_6, CType(6, Short))
			//Me.lblLabels.SetIndex(_lblLabels_7, CType(7, Short))
			//Me.lblLabels.SetIndex(_lblLabels_8, CType(8, Short))
			//Me.lblLabels.SetIndex(_lblLabels_9, CType(9, Short))
			//Me.lblLabels.SetIndex(_lblLabels_13, CType(13, Short))
			//Me.lblLabels.SetIndex(_lblLabels_14, CType(14, Short))
			//Me.lblLabels.SetIndex(_lblLabels_15, CType(15, Short))
			//Me.lblLabels.SetIndex(_lblLabels_16, CType(16, Short))
			//Me.lblLabels.SetIndex(_lblLabels_17, CType(17, Short))
			//Me.txtFields.SetIndex(_txtFields_28, CType(28, Short))
			//Me.txtFields.SetIndex(_txtFields_27, CType(27, Short))
			//Me.txtFields.SetIndex(_txtFields_26, CType(26, Short))
			//Me.txtFields.SetIndex(_txtFields_1, CType(1, Short))
			//Me.txtFields.SetIndex(_txtFields_2, CType(2, Short))
			//Me.txtFields.SetIndex(_txtFields_6, CType(6, Short))
			//Me.txtFields.SetIndex(_txtFields_7, CType(7, Short))
			//Me.txtFields.SetIndex(_txtFields_8, CType(8, Short))
			//Me.txtFields.SetIndex(_txtFields_9, CType(9, Short))
			//Me.txtFloat.SetIndex(_txtFloat_13, CType(13, Short))
			//Me.txtFloat.SetIndex(_txtFloat_14, CType(14, Short))
			//Me.txtFloat.SetIndex(_txtFloat_15, CType(15, Short))
			//M() ''e.txtFloat.SetIndex(_txtFloat_16, CType(16, Short))
			//M() 'e.txtFloat.SetIndex(_txtFloat_17, CType(17, Short))
			//M() 'e.txtFloatNegative.SetIndex(_txtFloatNegative_11, CType(11, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_12, CType(12, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_13, CType(13, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_14, CType(14, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_15, CType(15, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_16, CType(16, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_17, CType(17, Short))
			//Me.txtFloatNegative.SetIndex(_txtFloatNegative_18, CType(18, Short))
			this.Shape1.SetIndex(_Shape1_0, Convert.ToInt16(0));
			this.Shape1.SetIndex(_Shape1_1, Convert.ToInt16(1));
			this.Shape1.SetIndex(_Shape1_2, Convert.ToInt16(2));
			this.Shape1.SetIndex(_Shape1_3, Convert.ToInt16(3));
			((System.ComponentModel.ISupportInitialize)this.Shape1).EndInit();
			//CType(Me.txtFloatNegative, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.txtFloat, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.txtFields, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.lblLabels, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.lbl, System.ComponentModel.ISupportInitialize).EndInit()
			//CType(Me.chkFields, System.ComponentModel.ISupportInitialize).EndInit()
			((System.ComponentModel.ISupportInitialize)this.cmbTemplate).EndInit();
			this.picButtons.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
